// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         projectId: "projectId",
 *         environmentId: "environmentId",
 *         apiKeyId: "apiKeyId"
 *     }
 */
export interface ApiKeysGetRequest {
  organizationId: string;
  projectId: string;
  environmentId: string;
  apiKeyId: string;
}
