// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";

export const TokenCostCalculateRequestUsage: core.serialization.ObjectSchema<
  serializers.TokenCostCalculateRequestUsage.Raw,
  Mirascope.TokenCostCalculateRequestUsage
> = core.serialization.object({
  inputTokens: core.serialization.number(),
  outputTokens: core.serialization.number(),
  cacheReadTokens: core.serialization.number().optional(),
  cacheWriteTokens: core.serialization.number().optional(),
  cacheWriteBreakdown: core.serialization
    .record(core.serialization.string(), core.serialization.number())
    .optional(),
});

export declare namespace TokenCostCalculateRequestUsage {
  export interface Raw {
    inputTokens: number;
    outputTokens: number;
    cacheReadTokens?: number | null;
    cacheWriteTokens?: number | null;
    cacheWriteBreakdown?: Record<string, number> | null;
  }
}
