// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";

export const FunctionsCreateResponseDependenciesValue: core.serialization.ObjectSchema<
  serializers.FunctionsCreateResponseDependenciesValue.Raw,
  Mirascope.FunctionsCreateResponseDependenciesValue
> = core.serialization.object({
  version: core.serialization.string(),
  extras: core.serialization.list(core.serialization.string()).nullable(),
});

export declare namespace FunctionsCreateResponseDependenciesValue {
  export interface Raw {
    version: string;
    extras?: string[] | null;
  }
}
