// This file was auto-generated by Fern from our API Definition.

import type {
  BaseClientOptions,
  BaseRequestOptions,
} from "../../../../BaseClient.js";

import {
  type NormalizedClientOptions,
  normalizeClientOptions,
} from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import * as Mirascope from "../../../index.js";

export declare namespace ProjectsClient {
  export type Options = BaseClientOptions;

  export interface RequestOptions extends BaseRequestOptions {}
}

export class ProjectsClient {
  protected readonly _options: NormalizedClientOptions<ProjectsClient.Options>;

  constructor(options: ProjectsClient.Options = {}) {
    this._options = normalizeClientOptions(options);
  }

  /**
   * @param {Mirascope.ProjectsListRequest} request
   * @param {ProjectsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link Mirascope.BadRequestError}
   * @throws {@link Mirascope.ForbiddenError}
   * @throws {@link Mirascope.NotFoundError}
   * @throws {@link Mirascope.TooManyRequestsError}
   * @throws {@link Mirascope.InternalServerError}
   * @throws {@link Mirascope.ServiceUnavailableError}
   *
   * @example
   *     await client.projects.list({
   *         organizationId: "organizationId"
   *     })
   */
  public list(
    request: Mirascope.ProjectsListRequest,
    requestOptions?: ProjectsClient.RequestOptions,
  ): core.HttpResponsePromise<Mirascope.ProjectsListResponseItem[]> {
    return core.HttpResponsePromise.fromPromise(
      this.__list(request, requestOptions),
    );
  }

  private async __list(
    request: Mirascope.ProjectsListRequest,
    requestOptions?: ProjectsClient.RequestOptions,
  ): Promise<core.WithRawResponse<Mirascope.ProjectsListResponseItem[]>> {
    const { organizationId } = request;
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.MirascopeEnvironment.Production,
        `organizations/${core.url.encodePathParam(organizationId)}/projects`,
      ),
      method: "GET",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        (requestOptions?.timeoutInSeconds ??
          this._options?.timeoutInSeconds ??
          180) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: serializers.projects.list.Response.parseOrThrow(_response.body, {
          unrecognizedObjectKeys: "passthrough",
          allowUnrecognizedUnionMembers: true,
          allowUnrecognizedEnumValues: true,
          skipValidation: true,
          breadcrumbsPrefix: ["response"],
        }),
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new Mirascope.BadRequestError(
            _response.error.body,
            _response.rawResponse,
          );
        case 403:
          throw new Mirascope.ForbiddenError(
            serializers.PermissionDeniedError.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 404:
          throw new Mirascope.NotFoundError(
            serializers.NotFoundErrorBody.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 429:
          throw new Mirascope.TooManyRequestsError(
            serializers.RateLimitError.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 500:
          throw new Mirascope.InternalServerError(
            _response.error.body,
            _response.rawResponse,
          );
        case 503:
          throw new Mirascope.ServiceUnavailableError(
            _response.error.body,
            _response.rawResponse,
          );
        default:
          throw new errors.MirascopeError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "GET",
      "/organizations/{organizationId}/projects",
    );
  }

  /**
   * @param {Mirascope.ProjectsCreateRequest} request
   * @param {ProjectsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link Mirascope.BadRequestError}
   * @throws {@link Mirascope.PaymentRequiredError}
   * @throws {@link Mirascope.ForbiddenError}
   * @throws {@link Mirascope.NotFoundError}
   * @throws {@link Mirascope.ConflictError}
   * @throws {@link Mirascope.TooManyRequestsError}
   * @throws {@link Mirascope.InternalServerError}
   * @throws {@link Mirascope.ServiceUnavailableError}
   *
   * @example
   *     await client.projects.create({
   *         organizationId: "organizationId",
   *         name: "name",
   *         slug: "slug"
   *     })
   */
  public create(
    request: Mirascope.ProjectsCreateRequest,
    requestOptions?: ProjectsClient.RequestOptions,
  ): core.HttpResponsePromise<Mirascope.ProjectsCreateResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__create(request, requestOptions),
    );
  }

  private async __create(
    request: Mirascope.ProjectsCreateRequest,
    requestOptions?: ProjectsClient.RequestOptions,
  ): Promise<core.WithRawResponse<Mirascope.ProjectsCreateResponse>> {
    const { organizationId, ..._body } = request;
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.MirascopeEnvironment.Production,
        `organizations/${core.url.encodePathParam(organizationId)}/projects`,
      ),
      method: "POST",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: serializers.ProjectsCreateRequest.jsonOrThrow(_body, {
        unrecognizedObjectKeys: "strip",
        omitUndefined: true,
      }),
      timeoutMs:
        (requestOptions?.timeoutInSeconds ??
          this._options?.timeoutInSeconds ??
          180) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: serializers.ProjectsCreateResponse.parseOrThrow(_response.body, {
          unrecognizedObjectKeys: "passthrough",
          allowUnrecognizedUnionMembers: true,
          allowUnrecognizedEnumValues: true,
          skipValidation: true,
          breadcrumbsPrefix: ["response"],
        }),
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new Mirascope.BadRequestError(
            _response.error.body,
            _response.rawResponse,
          );
        case 402:
          throw new Mirascope.PaymentRequiredError(
            serializers.PlanLimitExceededError.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 403:
          throw new Mirascope.ForbiddenError(
            serializers.PermissionDeniedError.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 404:
          throw new Mirascope.NotFoundError(
            serializers.NotFoundErrorBody.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 409:
          throw new Mirascope.ConflictError(
            _response.error.body,
            _response.rawResponse,
          );
        case 429:
          throw new Mirascope.TooManyRequestsError(
            serializers.RateLimitError.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 500:
          throw new Mirascope.InternalServerError(
            _response.error.body,
            _response.rawResponse,
          );
        case 503:
          throw new Mirascope.ServiceUnavailableError(
            _response.error.body,
            _response.rawResponse,
          );
        default:
          throw new errors.MirascopeError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "POST",
      "/organizations/{organizationId}/projects",
    );
  }

  /**
   * @param {Mirascope.ProjectsGetRequest} request
   * @param {ProjectsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link Mirascope.BadRequestError}
   * @throws {@link Mirascope.ForbiddenError}
   * @throws {@link Mirascope.NotFoundError}
   * @throws {@link Mirascope.TooManyRequestsError}
   * @throws {@link Mirascope.InternalServerError}
   * @throws {@link Mirascope.ServiceUnavailableError}
   *
   * @example
   *     await client.projects.get({
   *         organizationId: "organizationId",
   *         projectId: "projectId"
   *     })
   */
  public get(
    request: Mirascope.ProjectsGetRequest,
    requestOptions?: ProjectsClient.RequestOptions,
  ): core.HttpResponsePromise<Mirascope.ProjectsGetResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__get(request, requestOptions),
    );
  }

  private async __get(
    request: Mirascope.ProjectsGetRequest,
    requestOptions?: ProjectsClient.RequestOptions,
  ): Promise<core.WithRawResponse<Mirascope.ProjectsGetResponse>> {
    const { organizationId, projectId } = request;
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.MirascopeEnvironment.Production,
        `organizations/${core.url.encodePathParam(organizationId)}/projects/${core.url.encodePathParam(projectId)}`,
      ),
      method: "GET",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        (requestOptions?.timeoutInSeconds ??
          this._options?.timeoutInSeconds ??
          180) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: serializers.ProjectsGetResponse.parseOrThrow(_response.body, {
          unrecognizedObjectKeys: "passthrough",
          allowUnrecognizedUnionMembers: true,
          allowUnrecognizedEnumValues: true,
          skipValidation: true,
          breadcrumbsPrefix: ["response"],
        }),
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new Mirascope.BadRequestError(
            _response.error.body,
            _response.rawResponse,
          );
        case 403:
          throw new Mirascope.ForbiddenError(
            serializers.PermissionDeniedError.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 404:
          throw new Mirascope.NotFoundError(
            serializers.NotFoundErrorBody.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 429:
          throw new Mirascope.TooManyRequestsError(
            serializers.RateLimitError.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 500:
          throw new Mirascope.InternalServerError(
            _response.error.body,
            _response.rawResponse,
          );
        case 503:
          throw new Mirascope.ServiceUnavailableError(
            _response.error.body,
            _response.rawResponse,
          );
        default:
          throw new errors.MirascopeError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "GET",
      "/organizations/{organizationId}/projects/{projectId}",
    );
  }

  /**
   * @param {Mirascope.ProjectsUpdateRequest} request
   * @param {ProjectsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link Mirascope.BadRequestError}
   * @throws {@link Mirascope.ForbiddenError}
   * @throws {@link Mirascope.NotFoundError}
   * @throws {@link Mirascope.ConflictError}
   * @throws {@link Mirascope.TooManyRequestsError}
   * @throws {@link Mirascope.InternalServerError}
   * @throws {@link Mirascope.ServiceUnavailableError}
   *
   * @example
   *     await client.projects.update({
   *         organizationId: "organizationId",
   *         projectId: "projectId"
   *     })
   */
  public update(
    request: Mirascope.ProjectsUpdateRequest,
    requestOptions?: ProjectsClient.RequestOptions,
  ): core.HttpResponsePromise<Mirascope.ProjectsUpdateResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__update(request, requestOptions),
    );
  }

  private async __update(
    request: Mirascope.ProjectsUpdateRequest,
    requestOptions?: ProjectsClient.RequestOptions,
  ): Promise<core.WithRawResponse<Mirascope.ProjectsUpdateResponse>> {
    const { organizationId, projectId, ..._body } = request;
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.MirascopeEnvironment.Production,
        `organizations/${core.url.encodePathParam(organizationId)}/projects/${core.url.encodePathParam(projectId)}`,
      ),
      method: "PUT",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: serializers.ProjectsUpdateRequest.jsonOrThrow(_body, {
        unrecognizedObjectKeys: "strip",
        omitUndefined: true,
      }),
      timeoutMs:
        (requestOptions?.timeoutInSeconds ??
          this._options?.timeoutInSeconds ??
          180) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: serializers.ProjectsUpdateResponse.parseOrThrow(_response.body, {
          unrecognizedObjectKeys: "passthrough",
          allowUnrecognizedUnionMembers: true,
          allowUnrecognizedEnumValues: true,
          skipValidation: true,
          breadcrumbsPrefix: ["response"],
        }),
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new Mirascope.BadRequestError(
            _response.error.body,
            _response.rawResponse,
          );
        case 403:
          throw new Mirascope.ForbiddenError(
            serializers.PermissionDeniedError.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 404:
          throw new Mirascope.NotFoundError(
            serializers.NotFoundErrorBody.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 409:
          throw new Mirascope.ConflictError(
            _response.error.body,
            _response.rawResponse,
          );
        case 429:
          throw new Mirascope.TooManyRequestsError(
            serializers.RateLimitError.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 500:
          throw new Mirascope.InternalServerError(
            _response.error.body,
            _response.rawResponse,
          );
        case 503:
          throw new Mirascope.ServiceUnavailableError(
            _response.error.body,
            _response.rawResponse,
          );
        default:
          throw new errors.MirascopeError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "PUT",
      "/organizations/{organizationId}/projects/{projectId}",
    );
  }

  /**
   * @param {Mirascope.ProjectsDeleteRequest} request
   * @param {ProjectsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link Mirascope.BadRequestError}
   * @throws {@link Mirascope.ForbiddenError}
   * @throws {@link Mirascope.NotFoundError}
   * @throws {@link Mirascope.TooManyRequestsError}
   * @throws {@link Mirascope.InternalServerError}
   * @throws {@link Mirascope.ServiceUnavailableError}
   *
   * @example
   *     await client.projects.delete({
   *         organizationId: "organizationId",
   *         projectId: "projectId"
   *     })
   */
  public delete(
    request: Mirascope.ProjectsDeleteRequest,
    requestOptions?: ProjectsClient.RequestOptions,
  ): core.HttpResponsePromise<void> {
    return core.HttpResponsePromise.fromPromise(
      this.__delete(request, requestOptions),
    );
  }

  private async __delete(
    request: Mirascope.ProjectsDeleteRequest,
    requestOptions?: ProjectsClient.RequestOptions,
  ): Promise<core.WithRawResponse<void>> {
    const { organizationId, projectId } = request;
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.MirascopeEnvironment.Production,
        `organizations/${core.url.encodePathParam(organizationId)}/projects/${core.url.encodePathParam(projectId)}`,
      ),
      method: "DELETE",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        (requestOptions?.timeoutInSeconds ??
          this._options?.timeoutInSeconds ??
          180) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return { data: undefined, rawResponse: _response.rawResponse };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new Mirascope.BadRequestError(
            _response.error.body,
            _response.rawResponse,
          );
        case 403:
          throw new Mirascope.ForbiddenError(
            serializers.PermissionDeniedError.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 404:
          throw new Mirascope.NotFoundError(
            serializers.NotFoundErrorBody.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 429:
          throw new Mirascope.TooManyRequestsError(
            serializers.RateLimitError.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 500:
          throw new Mirascope.InternalServerError(
            _response.error.body,
            _response.rawResponse,
          );
        case 503:
          throw new Mirascope.ServiceUnavailableError(
            _response.error.body,
            _response.rawResponse,
          );
        default:
          throw new errors.MirascopeError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "DELETE",
      "/organizations/{organizationId}/projects/{projectId}",
    );
  }
}
