// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../../api/index.js";
import type * as serializers from "../../../../index.js";

import * as core from "../../../../../core/index.js";

export const ProjectsUpdateRequest: core.serialization.Schema<
  serializers.ProjectsUpdateRequest.Raw,
  Omit<Mirascope.ProjectsUpdateRequest, "organizationId" | "projectId">
> = core.serialization.object({
  name: core.serialization.string().optional(),
  slug: core.serialization.string().optional(),
});

export declare namespace ProjectsUpdateRequest {
  export interface Raw {
    name?: string | null;
    slug?: string | null;
  }
}
