import { cloudflare } from "@cloudflare/vite-plugin";
import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import path from "path";
import { viteMDX } from "./vite-plugins/mdx";
import { viteContent } from "./vite-plugins/content";
import { viteImages } from "./vite-plugins/images";
import { viteRobots } from "./vite-plugins/robots";
import { defineConfig } from "vite";

export default defineConfig(() => {
  const contentDir = path.resolve(process.cwd(), "content");
  return {
    server: {
      port: 3000,
    },
    plugins: [
      viteContent({ contentDir }),
      viteMDX(),
      viteImages({ viteEnvironments: ["client"] }),
      cloudflare({ viteEnvironment: { name: "ssr" } }),
      tanstackStart({
        srcDirectory: "app",
        pages,
        prerender: {
          enabled: true,
          crawlLinks: true,
          autoStaticPathsDiscovery: true,
          autoSubfolderIndex: false,
          concurrency: 14,
          // NOTE: Bug in TanStack Start that explicit retries will let 404 errors slip through.
          retryCount: 0,
          retryDelay: 0,
          maxRedirects: 5,
          failOnError: true,
          // for now, pages not included in prerendering will be disallowed in robots.txt
          filter: (page: { path: string }) =>
            page.path.startsWith("/home") ||
            page.path.startsWith("/pricing") ||
            page.path.startsWith("/docs") ||
            page.path.startsWith("/blog") ||
            page.path.startsWith("/terms") ||
            page.path.startsWith("/privacy"),
          // todo(sebastian): Consider post-processing sitemap/pages to set the changefreq.
          // When using autoStaticPathsDiscovery, you can't set the sitemap changefreq or
          // other sitemap options per page—frequency can only be set on a per-page basis if you provide
          // an explicit pages array. For auto-discovered pages, control over frequency is not available.
          onSuccess: ({ page }: { page: { path: string } }) => {
            console.log(`Rendered ${page.path}!`);
            let changefreq = "daily";
            if (page.path.startsWith("/blog/")) {
              changefreq = "weekly";
            }
            return { sitemap: { changefreq } };
          },
        },
        sitemap: {
          enabled: true,
          host: "https://mirascope.com",
        },
      }),
      viteRobots(), // Generate robots disallow paths from sitemap (must be after tanstackStart)
      viteReact(),
      tailwindcss(),
    ],
    resolve: {
      alias: {
        "@": path.resolve(__dirname, "./"),
      },
    },
  };
});

// todo(sebastian): Generate dynamically with a subset of content processor
const pages = [
  { path: "/blog/prompt-testing" },
  { path: "/blog/prompt-orchestration" },
  { path: "/blog/prompt-management-system" },
  { path: "/blog/prompt-iteration" },
  { path: "/blog/prompt-editor" },
  { path: "/blog/llm-application-development" },
  { path: "/blog/context-engineering-platform" },
  { path: "/blog/prompt-testing-framework" },
  { path: "/blog/prompt-management-tool" },
  { path: "/blog/llm-monitoring-tools" },
  { path: "/blog/langsmith-vs-langfuse" },
  { path: "/blog/langchain-vs-langsmith" },
  { path: "/blog/context-engineering" },
  { path: "/blog/llm-observability" },
  { path: "/blog/langfuse-prompt-management" },
  { path: "/blog/prompt-optimization" },
  { path: "/blog/prompt-engineering-best-practices" },
  { path: "/blog/langchain-sucks" },
  { path: "/blog/langchain-structured-output" },
  { path: "/blog/langchain-prompt-template" },
  { path: "/blog/advanced-prompt-engineering" },
  { path: "/blog/langchain-alternatives" },
  { path: "/blog/langsmith-prompt-management" },
  { path: "/blog/langfuse-alternatives" },
  { path: "/blog/langsmith-alternatives" },
  { path: "/blog/prompt-engineering-tools" },
  { path: "/blog/prompt-versioning" },
  { path: "/blog/prompt-evaluation" },
  { path: "/blog/llm-integration" },
  { path: "/blog/llm-chaining" },
  { path: "/blog/llm-agents" },
  { path: "/blog/how-to-make-a-chatbot" },
  { path: "/blog/llm-as-judge" },
  { path: "/blog/synthetic-data-generation" },
  { path: "/blog/rag-application" },
  { path: "/blog/rag-llm-example" },
  { path: "/blog/llm-frameworks" },
  { path: "/blog/how-to-build-a-knowledge-graph" },
  { path: "/blog/langchain-rag" },
  { path: "/blog/llm-evaluation" },
  { path: "/blog/prompt-engineering-vs-fine-tuning" },
  { path: "/blog/llm-prompt" },
  { path: "/blog/llm-applications" },
  { path: "/blog/mirascope-v1-release" },
  { path: "/blog/llm-orchestration" },
  { path: "/blog/llm-pipeline" },
  { path: "/blog/llm-tools" },
  { path: "/blog/openai-function-calling" },
  { path: "/blog/prompt-engineering-examples" },
  { path: "/blog/langchain-runnables" },
  { path: "/blog/prompt-chaining" },
  { path: "/blog/langfuse-integration" },
  { path: "/blog/llamaindex-vs-langchain" },
  { path: "/blog/prompt-flow-vs-langchain" },
  { path: "/blog/engineers-should-handle-prompting-llms" },
  { path: "/docs" },
  { path: "/docs/examples" },
  { path: "/docs/v1" },
  { path: "/docs/v1/learn/tools" },
  { path: "/docs/v1/learn/streams" },
  { path: "/docs/v1/learn/retries" },
  { path: "/docs/v1/learn/response_models" },
  { path: "/docs/v1/learn/prompts" },
  { path: "/docs/v1/learn/output_parsers" },
  { path: "/docs/v1/learn/local_models" },
  { path: "/docs/v1/learn/json_mode" },
  { path: "/docs/v1/learn" },
  { path: "/docs/v1/learn/evals" },
  { path: "/docs/v1/learn/chaining" },
  { path: "/docs/v1/learn/calls" },
  { path: "/docs/v1/learn/async" },
  { path: "/docs/v1/learn/agents" },
  { path: "/docs/v1/guides" },
  { path: "/docs/v1/getting-started/why" },
  { path: "/docs/v1/getting-started/migration" },
  { path: "/docs/v1/getting-started/help" },
  { path: "/docs/v1/getting-started/contributing" },
  { path: "/docs/v1/api" },
  { path: "/docs/v1/learn/provider-specific/thinking-and-reasoning" },
  { path: "/docs/v1/learn/provider-specific/openai" },
  { path: "/docs/v1/learn/provider-specific/anthropic" },
  { path: "/docs/v1/learn/mcp/client" },
  { path: "/docs/v1/learn/extensions/middleware" },
  { path: "/docs/v1/learn/extensions/custom_provider" },
  { path: "/docs/v1/guides/more-advanced/text-translation" },
  { path: "/docs/v1/guides/more-advanced/text-summarization" },
  { path: "/docs/v1/guides/more-advanced/text-classification" },
  { path: "/docs/v1/guides/more-advanced/support-ticket-routing" },
  { path: "/docs/v1/guides/more-advanced/speech-transcription" },
  { path: "/docs/v1/guides/more-advanced/search-with-sources" },
  { path: "/docs/v1/guides/more-advanced/removing-semantic-duplicates" },
  { path: "/docs/v1/guides/more-advanced/query-plan" },
  { path: "/docs/v1/guides/more-advanced/pii-scrubbing" },
  { path: "/docs/v1/guides/more-advanced/o1-style-thinking" },
  { path: "/docs/v1/guides/more-advanced/named-entity-recognition" },
  { path: "/docs/v1/guides/more-advanced/llm-validation-with-retries" },
  { path: "/docs/v1/guides/more-advanced/knowledge-graph" },
  { path: "/docs/v1/guides/more-advanced/generating-synthetic-data" },
  { path: "/docs/v1/guides/more-advanced/generating-captions" },
  { path: "/docs/v1/guides/more-advanced/extraction-using-vision" },
  { path: "/docs/v1/guides/more-advanced/extract-from-pdf" },
  { path: "/docs/v1/guides/more-advanced/document-segmentation" },
  { path: "/docs/v1/guides/more-advanced/code-generation-and-execution" },
  { path: "/docs/v1/guides/langgraph-vs-mirascope/quickstart" },
  { path: "/docs/v1/guides/getting-started/tools-and-agents" },
  { path: "/docs/v1/guides/getting-started/structured-outputs" },
  { path: "/docs/v1/guides/getting-started/quickstart" },
  {
    path: "/docs/v1/guides/getting-started/dynamic-configuration-and-chaining",
  },
  { path: "/docs/v1/guides/agents/web-search-agent" },
  { path: "/docs/v1/guides/agents/sql-agent" },
  { path: "/docs/v1/guides/agents/qwant-search-agent-with-sources" },
  { path: "/docs/v1/guides/agents/localized-agent" },
  { path: "/docs/v1/guides/agents/local-chat-with-codebase" },
  { path: "/docs/v1/guides/agents/documentation-agent" },
  { path: "/docs/v1/guides/agents/blog-writing-agent" },
  { path: "/docs/v1/guides/evals/evaluating-web-search-agent" },
  { path: "/docs/v1/guides/evals/evaluating-sql-agent" },
  { path: "/docs/v1/guides/evals/evaluating-documentation-agent" },
  { path: "/docs/v1/api/mcp/client" },
  { path: "/docs/v1/api/retries/tenacity" },
  { path: "/docs/v1/api/retries/fallback" },
  { path: "/docs/v1/api/llm/tool" },
  { path: "/docs/v1/api/llm/stream" },
  { path: "/docs/v1/api/llm/override" },
  { path: "/docs/v1/api/llm/context" },
  { path: "/docs/v1/api/llm/call_response_chunk" },
  { path: "/docs/v1/api/llm/call_response" },
  { path: "/docs/v1/api/llm/call" },
  { path: "/docs/v1/guides/prompt-engineering/text-based/thread-of-thought" },
  {
    path: "/docs/v1/guides/prompt-engineering/text-based/tabular-chain-of-thought",
  },
  { path: "/docs/v1/guides/prompt-engineering/text-based/self-ask" },
  { path: "/docs/v1/guides/prompt-engineering/text-based/role-prompting" },
  { path: "/docs/v1/guides/prompt-engineering/text-based/rereading" },
  {
    path: "/docs/v1/guides/prompt-engineering/text-based/rephrase-and-respond",
  },
  { path: "/docs/v1/guides/prompt-engineering/text-based/plan-and-solve" },
  { path: "/docs/v1/guides/prompt-engineering/text-based/emotion-prompting" },
  {
    path: "/docs/v1/guides/prompt-engineering/text-based/contrastive-chain-of-thought",
  },
  { path: "/docs/v1/guides/prompt-engineering/text-based/common-phrases" },
  { path: "/docs/v1/guides/prompt-engineering/text-based/chain-of-thought" },
  {
    path: "/docs/v1/guides/prompt-engineering/chaining-based/system-to-attention",
  },
  { path: "/docs/v1/guides/prompt-engineering/chaining-based/step-back" },
  {
    path: "/docs/v1/guides/prompt-engineering/chaining-based/skeleton-of-thought",
  },
  { path: "/docs/v1/guides/prompt-engineering/chaining-based/sim-to-m" },
  { path: "/docs/v1/guides/prompt-engineering/chaining-based/self-refine" },
  {
    path: "/docs/v1/guides/prompt-engineering/chaining-based/self-consistency",
  },
  {
    path: "/docs/v1/guides/prompt-engineering/chaining-based/reverse-chain-of-thought",
  },
  {
    path: "/docs/v1/guides/prompt-engineering/chaining-based/prompt-paraphrasing",
  },
  {
    path: "/docs/v1/guides/prompt-engineering/chaining-based/mixture-of-reasoning",
  },
  { path: "/docs/v1/guides/prompt-engineering/chaining-based/least-to-most" },
  { path: "/docs/v1/guides/prompt-engineering/chaining-based/diverse" },
  {
    path: "/docs/v1/guides/prompt-engineering/chaining-based/demonstration-ensembling",
  },
  {
    path: "/docs/v1/guides/prompt-engineering/chaining-based/decomposed-prompting",
  },
  {
    path: "/docs/v1/guides/prompt-engineering/chaining-based/chain-of-verification",
  },
  { path: "/docs/v1/api/tools/system/file_system" },
  { path: "/docs/v1/api/tools/system/docker_operation" },
  { path: "/docs/v1/api/tools/web/requests" },
  { path: "/docs/v1/api/tools/web/parse_url_content" },
  { path: "/docs/v1/api/tools/web/httpx" },
  { path: "/docs/v1/api/tools/web/duckduckgo" },
  { path: "/docs/v1/api/core/xai/tool" },
  { path: "/docs/v1/api/core/xai/stream" },
  { path: "/docs/v1/api/core/xai/dynamic_config" },
  { path: "/docs/v1/api/core/xai/call_response_chunk" },
  { path: "/docs/v1/api/core/xai/call_response" },
  { path: "/docs/v1/api/core/xai/call_params" },
  { path: "/docs/v1/api/core/xai/call" },
  { path: "/docs/v1/api/core/openai/tool" },
  { path: "/docs/v1/api/core/openai/stream" },
  { path: "/docs/v1/api/core/openai/dynamic_config" },
  { path: "/docs/v1/api/core/openai/call_response_chunk" },
  { path: "/docs/v1/api/core/openai/call_response" },
  { path: "/docs/v1/api/core/openai/call_params" },
  { path: "/docs/v1/api/core/openai/call" },
  { path: "/docs/v1/api/core/mistral/tool" },
  { path: "/docs/v1/api/core/mistral/stream" },
  { path: "/docs/v1/api/core/mistral/dynamic_config" },
  { path: "/docs/v1/api/core/mistral/call_response_chunk" },
  { path: "/docs/v1/api/core/mistral/call_response" },
  { path: "/docs/v1/api/core/mistral/call_params" },
  { path: "/docs/v1/api/core/mistral/call" },
  { path: "/docs/v1/api/core/google/tool" },
  { path: "/docs/v1/api/core/google/stream" },
  { path: "/docs/v1/api/core/google/dynamic_config" },
  { path: "/docs/v1/api/core/google/call_response_chunk" },
  { path: "/docs/v1/api/core/google/call_response" },
  { path: "/docs/v1/api/core/google/call_params" },
  { path: "/docs/v1/api/core/google/call" },
  { path: "/docs/v1/api/core/groq/tool" },
  { path: "/docs/v1/api/core/groq/stream" },
  { path: "/docs/v1/api/core/groq/dynamic_config" },
  { path: "/docs/v1/api/core/groq/call_response_chunk" },
  { path: "/docs/v1/api/core/groq/call_response" },
  { path: "/docs/v1/api/core/groq/call_params" },
  { path: "/docs/v1/api/core/groq/call" },
  { path: "/docs/v1/api/core/litellm/tool" },
  { path: "/docs/v1/api/core/litellm/stream" },
  { path: "/docs/v1/api/core/litellm/dynamic_config" },
  { path: "/docs/v1/api/core/litellm/call_response_chunk" },
  { path: "/docs/v1/api/core/litellm/call_response" },
  { path: "/docs/v1/api/core/litellm/call_params" },
  { path: "/docs/v1/api/core/litellm/call" },
  { path: "/docs/v1/api/core/costs/calculate_cost" },
  { path: "/docs/v1/api/core/bedrock/tool" },
  { path: "/docs/v1/api/core/bedrock/stream" },
  { path: "/docs/v1/api/core/bedrock/dynamic_config" },
  { path: "/docs/v1/api/core/bedrock/call_response_chunk" },
  { path: "/docs/v1/api/core/bedrock/call_response" },
  { path: "/docs/v1/api/core/bedrock/call_params" },
  { path: "/docs/v1/api/core/bedrock/call" },
  { path: "/docs/v1/api/core/cohere/tool" },
  { path: "/docs/v1/api/core/cohere/stream" },
  { path: "/docs/v1/api/core/cohere/dynamic_config" },
  { path: "/docs/v1/api/core/cohere/call_response_chunk" },
  { path: "/docs/v1/api/core/cohere/call_response" },
  { path: "/docs/v1/api/core/cohere/call_params" },
  { path: "/docs/v1/api/core/cohere/call" },
  { path: "/docs/v1/api/core/anthropic/tool" },
  { path: "/docs/v1/api/core/anthropic/stream" },
  { path: "/docs/v1/api/core/anthropic/dynamic_config" },
  { path: "/docs/v1/api/core/anthropic/call_response_chunk" },
  { path: "/docs/v1/api/core/anthropic/call_response" },
  { path: "/docs/v1/api/core/anthropic/call_params" },
  { path: "/docs/v1/api/core/anthropic/call" },
  { path: "/docs/v1/api/core/base/types" },
  { path: "/docs/v1/api/core/base/toolkit" },
  { path: "/docs/v1/api/core/base/tool" },
  { path: "/docs/v1/api/core/base/structured_stream" },
  { path: "/docs/v1/api/core/base/stream" },
  { path: "/docs/v1/api/core/base/prompt" },
  { path: "/docs/v1/api/core/base/metadata" },
  { path: "/docs/v1/api/core/base/message_param" },
  { path: "/docs/v1/api/core/base/merge_decorators" },
  { path: "/docs/v1/api/core/base/dynamic_config" },
  { path: "/docs/v1/api/core/base/call_response_chunk" },
  { path: "/docs/v1/api/core/base/call_response" },
  { path: "/docs/v1/api/core/base/call_params" },
  { path: "/docs/v1/api/core/base/call_factory" },
  { path: "/docs/v1/api/core/azure/tool" },
  { path: "/docs/v1/api/core/azure/stream" },
  { path: "/docs/v1/api/core/azure/dynamic_config" },
  { path: "/docs/v1/api/core/azure/call_response_chunk" },
  { path: "/docs/v1/api/core/azure/call_response" },
  { path: "/docs/v1/api/core/azure/call_params" },
  { path: "/docs/v1/api/core/azure/call" },
  { path: "/privacy" },
  { path: "/terms/use" },
  { path: "/terms/service" },
];
