"""Retry response wrappers that add retry metadata to LLM responses."""

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any, Generic, overload

from ..content import (
    AssistantContentPart,
    Text,
    Thought,
    ToolCall,
    ToolOutput,
)
from ..formatting import Format, FormattableT
from ..messages import Message, UserContent
from ..responses import (
    AsyncResponse,
    FinishReason,
    Response,
    ResponseT,
    Usage,
)
from ..tools import (
    AsyncToolkit,
    Toolkit,
    ToolkitT,
)
from ..types import Jsonable
from .retry_config import RetryConfig

if TYPE_CHECKING:
    from ..models import Params
    from ..providers import ModelId, ProviderId
    from .retry_models import RetryModel


class BaseRetryResponse(Generic[ResponseT, ToolkitT, FormattableT]):
    """Base class for retry responses with shared delegation logic.

    This provides type-safe explicit delegation of all BaseResponse properties
    and methods to the wrapped response.
    """

    wrapped_response: ResponseT

    retry_config: RetryConfig

    @property
    def raw(self) -> Any:  # noqa: ANN401
        """The raw response from the LLM."""
        return self.wrapped_response.raw

    @property
    def provider_id(self) -> "ProviderId":
        """The provider that generated this response."""
        return self.wrapped_response.provider_id

    @property
    def model_id(self) -> "ModelId":
        """The model id that generated this response."""
        return self.wrapped_response.model_id

    @property
    def provider_model_name(self) -> str:
        """The provider-specific model name."""
        return self.wrapped_response.provider_model_name

    @property
    def params(self) -> "Params":
        """The params that were used to generate this response."""
        return self.wrapped_response.params

    @property
    def toolkit(self) -> ToolkitT:
        """The toolkit containing the tools used when generating this response."""
        return self.wrapped_response.toolkit

    @property
    def messages(self) -> list[Message]:
        """The message history, including the most recent assistant message."""
        return self.wrapped_response.messages

    @property
    def content(self) -> Sequence[AssistantContentPart]:
        """The content generated by the LLM."""
        return self.wrapped_response.content

    @property
    def texts(self) -> Sequence[Text]:
        """The text content in the generated response, if any."""
        return self.wrapped_response.texts

    @property
    def tool_calls(self) -> Sequence[ToolCall]:
        """The tools the LLM wants called on its behalf, if any."""
        return self.wrapped_response.tool_calls

    @property
    def thoughts(self) -> Sequence[Thought]:
        """The readable thoughts from the model's thinking process, if any."""
        return self.wrapped_response.thoughts

    @property
    def finish_reason(self) -> FinishReason | None:
        """The reason why the LLM finished generating a response, if set."""
        return self.wrapped_response.finish_reason

    @property
    def format(self) -> Format[FormattableT] | None:
        """The Format describing the structured response format, if available."""
        return self.wrapped_response.format

    @property
    def model(self) -> "RetryModel":
        """A RetryModel with parameters matching this response."""

        from .retry_models import RetryModel  # Lazy import to avoid circular dependency

        return RetryModel(self.wrapped_response.model, self.retry_config)

    @property
    def usage(self) -> Usage | None:
        """The token usage of this response, if available."""
        return self.wrapped_response.usage

    def parse(self) -> FormattableT | None:
        """Format the response according to the response format parser."""
        return self.wrapped_response.parse()

    def pretty(self) -> str:
        """Return a human-readable string representation of all response content."""
        return self.wrapped_response.pretty()


class RetryResponse(BaseRetryResponse[Response[FormattableT], Toolkit, FormattableT]):
    """Response wrapper that includes retry metadata.

    This wraps a successful `Response` and adds information about retry attempts,
    failures encountered, and any fallback models used.
    """

    def __init__(
        self, response: Response[FormattableT], retry_config: RetryConfig
    ) -> None:
        """Initialize a RetryResponse.

        Args:
            response: The successful response from the LLM.
            config: Configuration for retry behavior.
        """
        self.wrapped_response = response
        self.retry_config = retry_config

    def execute_tools(self) -> Sequence[ToolOutput[Jsonable]]:
        """Execute and return all of the tool calls in the response."""
        return self.wrapped_response.execute_tools()

    @overload
    def resume(
        self: "RetryResponse[None]", content: UserContent
    ) -> "RetryResponse[None]": ...

    @overload
    def resume(
        self: "RetryResponse[FormattableT]", content: UserContent
    ) -> "RetryResponse[FormattableT]": ...

    def resume(
        self, content: UserContent
    ) -> "RetryResponse[None] | RetryResponse[FormattableT]":
        """Generate a new RetryResponse using this response's messages with additional user content.

        Args:
            content: The new user message content to append to the message history.

        Returns:
            A new RetryResponse instance generated from the extended message history.
        """
        return self.model.resume(response=self.wrapped_response, content=content)


class AsyncRetryResponse(
    BaseRetryResponse[AsyncResponse[FormattableT], AsyncToolkit, FormattableT]
):
    """Async response wrapper that includes retry metadata.

    This wraps a successful `AsyncResponse` and adds information about retry attempts,
    failures encountered, and any fallback models used.
    """

    def __init__(
        self, response: AsyncResponse[FormattableT], retry_config: RetryConfig
    ) -> None:
        """Initialize an AsyncRetryResponse.

        Args:
            response: The successful async response from the LLM.
            config: Configuration for retry behavior.
        """
        self.wrapped_response = response
        self.retry_config = retry_config

    async def execute_tools(self) -> Sequence[ToolOutput[Jsonable]]:
        """Execute and return all of the tool calls in the response."""
        return await self.wrapped_response.execute_tools()

    @overload
    async def resume(
        self: "AsyncRetryResponse[None]", content: UserContent
    ) -> "AsyncRetryResponse[None]": ...

    @overload
    async def resume(
        self: "AsyncRetryResponse[FormattableT]", content: UserContent
    ) -> "AsyncRetryResponse[FormattableT]": ...

    async def resume(
        self, content: UserContent
    ) -> "AsyncRetryResponse[None] | AsyncRetryResponse[FormattableT]":
        """Generate a new AsyncRetryResponse using this response's messages with additional user content.

        Args:
            content: The new user message content to append to the message history.

        Returns:
            A new AsyncRetryResponse instance generated from the extended message history.
        """
        return await self.model.resume_async(
            response=self.wrapped_response, content=content
        )
