// This file was auto-generated by Fern from our API Definition.

export const ClawsCreateRequestModel = {
  ClaudeHaiku45: "claude-haiku-4-5",
  ClaudeSonnet45: "claude-sonnet-4-5",
  ClaudeOpus46: "claude-opus-4-6",
} as const;
export type ClawsCreateRequestModel =
  (typeof ClawsCreateRequestModel)[keyof typeof ClawsCreateRequestModel];
