# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.number_from_string import NumberFromString
from .raw_client import AsyncRawSdkAnnotationsClient, RawSdkAnnotationsClient
from .types.sdk_annotations_create_response import SdkAnnotationsCreateResponse
from .types.sdk_annotations_get_response import SdkAnnotationsGetResponse
from .types.sdk_annotations_list_response import SdkAnnotationsListResponse
from .types.sdk_annotations_update_response import SdkAnnotationsUpdateResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SdkAnnotationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSdkAnnotationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSdkAnnotationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSdkAnnotationsClient
        """
        return self._raw_client

    def sdk_annotations_list(
        self,
        *,
        trace_id: typing.Optional[str] = None,
        span_id: typing.Optional[str] = None,
        label: typing.Optional[str] = None,
        limit: typing.Optional[NumberFromString] = None,
        offset: typing.Optional[NumberFromString] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SdkAnnotationsListResponse:
        """
        Parameters
        ----------
        trace_id : typing.Optional[str]

        span_id : typing.Optional[str]

        label : typing.Optional[str]

        limit : typing.Optional[NumberFromString]

        offset : typing.Optional[NumberFromString]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SdkAnnotationsListResponse
            Success

        Examples
        --------
        from mirascope.api._generated import Mirascope

        client = Mirascope()
        client.sdk_annotations.sdk_annotations_list()
        """
        _response = self._raw_client.sdk_annotations_list(
            trace_id=trace_id,
            span_id=span_id,
            label=label,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    def sdk_annotations_create(
        self,
        *,
        span_id: str,
        trace_id: str,
        label: typing.Optional[str] = OMIT,
        reasoning: typing.Optional[str] = OMIT,
        data: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SdkAnnotationsCreateResponse:
        """
        Parameters
        ----------
        span_id : str

        trace_id : str

        label : typing.Optional[str]

        reasoning : typing.Optional[str]

        data : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SdkAnnotationsCreateResponse
            Success

        Examples
        --------
        from mirascope.api._generated import Mirascope

        client = Mirascope()
        client.sdk_annotations.sdk_annotations_create(
            span_id="spanId",
            trace_id="traceId",
        )
        """
        _response = self._raw_client.sdk_annotations_create(
            span_id=span_id,
            trace_id=trace_id,
            label=label,
            reasoning=reasoning,
            data=data,
            request_options=request_options,
        )
        return _response.data

    def sdk_annotations_get(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SdkAnnotationsGetResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SdkAnnotationsGetResponse
            Success

        Examples
        --------
        from mirascope.api._generated import Mirascope

        client = Mirascope()
        client.sdk_annotations.sdk_annotations_get(
            id="id",
        )
        """
        _response = self._raw_client.sdk_annotations_get(
            id, request_options=request_options
        )
        return _response.data

    def sdk_annotations_update(
        self,
        id: str,
        *,
        label: typing.Optional[str] = OMIT,
        reasoning: typing.Optional[str] = OMIT,
        data: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SdkAnnotationsUpdateResponse:
        """
        Parameters
        ----------
        id : str

        label : typing.Optional[str]

        reasoning : typing.Optional[str]

        data : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SdkAnnotationsUpdateResponse
            Success

        Examples
        --------
        from mirascope.api._generated import Mirascope

        client = Mirascope()
        client.sdk_annotations.sdk_annotations_update(
            id="id",
        )
        """
        _response = self._raw_client.sdk_annotations_update(
            id,
            label=label,
            reasoning=reasoning,
            data=data,
            request_options=request_options,
        )
        return _response.data

    def sdk_annotations_delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from mirascope.api._generated import Mirascope

        client = Mirascope()
        client.sdk_annotations.sdk_annotations_delete(
            id="id",
        )
        """
        _response = self._raw_client.sdk_annotations_delete(
            id, request_options=request_options
        )
        return _response.data


class AsyncSdkAnnotationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSdkAnnotationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSdkAnnotationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSdkAnnotationsClient
        """
        return self._raw_client

    async def sdk_annotations_list(
        self,
        *,
        trace_id: typing.Optional[str] = None,
        span_id: typing.Optional[str] = None,
        label: typing.Optional[str] = None,
        limit: typing.Optional[NumberFromString] = None,
        offset: typing.Optional[NumberFromString] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SdkAnnotationsListResponse:
        """
        Parameters
        ----------
        trace_id : typing.Optional[str]

        span_id : typing.Optional[str]

        label : typing.Optional[str]

        limit : typing.Optional[NumberFromString]

        offset : typing.Optional[NumberFromString]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SdkAnnotationsListResponse
            Success

        Examples
        --------
        import asyncio

        from mirascope.api._generated import AsyncMirascope

        client = AsyncMirascope()


        async def main() -> None:
            await client.sdk_annotations.sdk_annotations_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.sdk_annotations_list(
            trace_id=trace_id,
            span_id=span_id,
            label=label,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    async def sdk_annotations_create(
        self,
        *,
        span_id: str,
        trace_id: str,
        label: typing.Optional[str] = OMIT,
        reasoning: typing.Optional[str] = OMIT,
        data: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SdkAnnotationsCreateResponse:
        """
        Parameters
        ----------
        span_id : str

        trace_id : str

        label : typing.Optional[str]

        reasoning : typing.Optional[str]

        data : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SdkAnnotationsCreateResponse
            Success

        Examples
        --------
        import asyncio

        from mirascope.api._generated import AsyncMirascope

        client = AsyncMirascope()


        async def main() -> None:
            await client.sdk_annotations.sdk_annotations_create(
                span_id="spanId",
                trace_id="traceId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.sdk_annotations_create(
            span_id=span_id,
            trace_id=trace_id,
            label=label,
            reasoning=reasoning,
            data=data,
            request_options=request_options,
        )
        return _response.data

    async def sdk_annotations_get(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SdkAnnotationsGetResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SdkAnnotationsGetResponse
            Success

        Examples
        --------
        import asyncio

        from mirascope.api._generated import AsyncMirascope

        client = AsyncMirascope()


        async def main() -> None:
            await client.sdk_annotations.sdk_annotations_get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.sdk_annotations_get(
            id, request_options=request_options
        )
        return _response.data

    async def sdk_annotations_update(
        self,
        id: str,
        *,
        label: typing.Optional[str] = OMIT,
        reasoning: typing.Optional[str] = OMIT,
        data: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SdkAnnotationsUpdateResponse:
        """
        Parameters
        ----------
        id : str

        label : typing.Optional[str]

        reasoning : typing.Optional[str]

        data : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SdkAnnotationsUpdateResponse
            Success

        Examples
        --------
        import asyncio

        from mirascope.api._generated import AsyncMirascope

        client = AsyncMirascope()


        async def main() -> None:
            await client.sdk_annotations.sdk_annotations_update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.sdk_annotations_update(
            id,
            label=label,
            reasoning=reasoning,
            data=data,
            request_options=request_options,
        )
        return _response.data

    async def sdk_annotations_delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from mirascope.api._generated import AsyncMirascope

        client = AsyncMirascope()


        async def main() -> None:
            await client.sdk_annotations.sdk_annotations_delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.sdk_annotations_delete(
            id, request_options=request_options
        )
        return _response.data
