// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";
import { HealthCheckResponseStatus } from "./HealthCheckResponseStatus.js";

export const HealthCheckResponse: core.serialization.ObjectSchema<
  serializers.HealthCheckResponse.Raw,
  Mirascope.HealthCheckResponse
> = core.serialization.object({
  status: HealthCheckResponseStatus,
  timestamp: core.serialization.string(),
  environment: core.serialization.string(),
});

export declare namespace HealthCheckResponse {
  export interface Raw {
    status: HealthCheckResponseStatus.Raw;
    timestamp: string;
    environment: string;
  }
}
