// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";

export const HealthCheckResponseStatus: core.serialization.Schema<
  serializers.HealthCheckResponseStatus.Raw,
  Mirascope.HealthCheckResponseStatus
> = core.serialization.enum_(["ok"]);

export declare namespace HealthCheckResponseStatus {
  export type Raw = "ok";
}
