import { llm } from 'mirascope';

const textMessage = llm.messages.user('Hello, how are you?');

const image: llm.Image = {
  type: 'image',
  data: '/path/to/book-cover.jpg', // or URL, base64, or bytes
  mimeType: 'image/jpeg',
  id: 'book-cover', // optional
};
const imageMessage = llm.messages.user([
  'What book is shown in this image?',
  image,
]);

const audio: llm.Audio = {
  type: 'audio',
  data: '/path/to/audio-question.mp3', // or URL, base64, or bytes
  mimeType: 'audio/mp3',
  transcript: "What's your favorite book genre?", // optional
  id: 'audio-question', // optional
};
const audioMessage = llm.messages.user(audio);

const video: llm.Video = {
  type: 'video',
  data: '/path/to/book-review.mp4', // or URL, base64, or bytes
  mimeType: 'video/mp4',
  transcript: 'This is my review of The Martian...', // optional
  id: 'book-review', // optional
};
const videoMessage = llm.messages.user([
  'What do you think of this book review?',
  video,
]);

const document: llm.Document = {
  type: 'document',
  data: '/path/to/research-paper.pdf', // or URL, base64, or bytes
  mimeType: 'application/pdf',
};
const documentMessage = llm.messages.user([
  'Please summarize this research paper:',
  document,
]);

const toolCall: llm.ToolCall = {
  type: 'tool-call',
  id: 'call-weather-123', // generated by the model
  name: 'getCurrentWeather', // name of the tool to call
  args: { location: 'San Francisco, CA' }, // arguments for the tool
};
const toolCallMessage = llm.messages.assistant([toolCall]);

const toolOutput: llm.ToolOutput = {
  type: 'tool-output',
  id: 'call-weather-123', // matches the tool call ID
  value: { temperature: 72, condition: 'sunny', humidity: 45 }, // output from the tool
};
const toolOutputMessage = llm.messages.user([toolOutput]);

const thinking: llm.Thinking = {
  type: 'thinking',
  id: '1234...abcd', // generated by the model
  thoughts:
    'The user liked The Martian and Project Hail Mary, both hard sci-fi with problem-solving. They want similar themes but different settings. I should recommend books with clever protagonists facing technical challenges...',
  redacted: false,
};
const thinkingMessage = llm.messages.assistant([
  thinking,
  "Based on your love for Andy Weir's problem-solving narratives, I recommend 'Recursion' by Blake Crouch.",
]);

const mixedMessage = llm.messages.user([
  'I have a question about this book cover:',
  {
    type: 'image',
    data: 'https://coppermind.net/wiki/Mistborn:_The_Final_Empire/Covers#/media/File:TFE_US_1st_Cover.jpeg',
    mimeType: 'image/jpeg',
  },
  'Can you tell me what genre this appears to be?',
]);
