// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../index.js";

export interface TracesCreateOtelRequestResourceSpansItemScopeSpansItemScopeAttributesItemValue {
  stringValue?: string;
  intValue?: Mirascope.TracesCreateOtelRequestResourceSpansItemScopeSpansItemScopeAttributesItemValueIntValue;
  doubleValue?: number;
  boolValue?: boolean;
  arrayValue?: Mirascope.TracesCreateOtelRequestResourceSpansItemScopeSpansItemScopeAttributesItemValueArrayValue;
  kvlistValue?: Mirascope.TracesCreateOtelRequestResourceSpansItemScopeSpansItemScopeAttributesItemValueKvlistValue;
}
