// This file was auto-generated by Fern from our API Definition.

export const TracesSearchByEnvRequestSortBy = {
  StartTime: "start_time",
  DurationMs: "duration_ms",
  TotalTokens: "total_tokens",
} as const;
export type TracesSearchByEnvRequestSortBy =
  (typeof TracesSearchByEnvRequestSortBy)[keyof typeof TracesSearchByEnvRequestSortBy];
