// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../index.js";

export interface TracesCreateOtelRequestResourceSpansItemScopeSpansItemScope {
  name: string;
  version?: string;
  attributes?: Mirascope.TracesCreateOtelRequestResourceSpansItemScopeSpansItemScopeAttributesItem[];
  droppedAttributesCount?: number;
}
