// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../index.js";

export interface TracesListByFunctionHashResponse {
  traces: Mirascope.TracesListByFunctionHashResponseTracesItem[];
  total: number;
}
