from mirascope import llm

text_message = llm.messages.user("Hello, how are you?")

image = llm.Image(
    data="/path/to/book-cover.jpg",  # or URL, base64, or bytes
    mime_type="image/jpeg",
    id="book-cover",  # optional
)
image_message = llm.messages.user(["What book is shown in this image?", image])

audio = llm.Audio(
    data="/path/to/audio-question.mp3",  # or URL, base64, or bytes
    mime_type="audio/mp3",
    transcript="What's your favorite book genre?",  # optional
    id="audio-question",  # optional
)
audio_message = llm.messages.user(audio)

video = llm.Video(
    data="/path/to/book-review.mp4",  # or URL, base64, or bytes
    mime_type="video/mp4",
    transcript="This is my review of The Martian...",  # optional
    id="book-review",  # optional
)
video_message = llm.messages.user(["What do you think of this book review?", video])

document = llm.Document(
    data="/path/to/research-paper.pdf",  # or URL, base64, or bytes
    mime_type="application/pdf",
)
document_message = llm.messages.user(
    ["Please summarize this research paper:", document]
)

tool_call = llm.ToolCall(
    id="call_weather_123",
    name="get_current_weather",
    args={"location": "San Francisco, CA"},
)
tool_call_message = llm.messages.assistant([tool_call])

tool_output = llm.ToolOutput(
    id="call_weather_123",
    value={"temperature": 72, "condition": "sunny", "humidity": 45},
)
tool_output_message = llm.messages.user([tool_output])

thinking = llm.Thinking(
    id="1234...abcd",  # generated by the model
    thoughts="The user liked The Martian and Project Hail Mary, both hard sci-fi with problem-solving. They want similar themes but different settings. I should recommend books with clever protagonists facing technical challenges...",
    redacted=False,
)
thinking_message = llm.messages.assistant(
    [
        thinking,
        "Based on your love for Andy Weir's problem-solving narratives, I recommend 'Recursion' by Blake Crouch.",
    ]
)

mixed_message = llm.messages.user(
    [
        "I have a question about this book cover:",
        llm.Image(
            data="https://coppermind.net/wiki/Mistborn:_The_Final_Empire/Covers#/media/File:TFE_US_1st_Cover.jpeg",
            mime_type="image/jpeg",
        ),
        "Can you tell me what genre this appears to be?",
    ]
)
