"""The `Agent` class for LLM agents."""

from abc import ABC
from collections.abc import Sequence
from dataclasses import dataclass
from typing import Generic

from ..context import Context, DepsT
from ..formatting import FormatT
from ..messages import UserMessagePromotable
from ..models import LLM
from ..responses import AsyncStreamResponse, Response, StreamResponse
from ..tools import Tool

# TODO(@dandelion): Revisit Agent API for consistency on "run" vs "call", and on
# having clear arg types for query (vs UserMessagePromotable which may be opaque)


@dataclass
class BaseAgent(Generic[DepsT, FormatT], ABC):
    """Agent class for generating responses using LLMs with tools."""

    ctx: Context[DepsT]
    """The context for the agent, such as the history of messages."""

    tools: Sequence[Tool] | None
    """The tools available to the agent, if any."""

    format: type[FormatT] | None
    """The response format for the generated response."""

    model: LLM
    """The default model the agent will use if not specified through context."""

    async def run_async(
        self,
        query: UserMessagePromotable,
        *,
        ctx: Context[DepsT] | None = None,
    ) -> Response[FormatT]:
        """Generates a response by running the agent loop asynchronously."""
        raise NotImplementedError()

    async def stream_async(
        self,
        query: UserMessagePromotable,
        *,
        ctx: Context[DepsT] | None = None,
    ) -> AsyncStreamResponse[FormatT] | AsyncStreamResponse[FormatT]:
        """Streams the response generated by running the agent loop asynchronously."""
        raise NotImplementedError()


@dataclass
class Agent(BaseAgent[DepsT, FormatT]):
    """Agent class for generating responses using LLMs with tools."""

    def __call__(
        self,
        query: UserMessagePromotable,
        *,
        ctx: Context[DepsT] | None = None,
    ) -> Response[FormatT]:
        """Generates a response by running the agent loop."""
        raise NotImplementedError()

    def call(
        self,
        query: UserMessagePromotable,
        *,
        ctx: Context[DepsT] | None = None,
    ) -> Response[FormatT]:
        """Generates a response by running the agent loop."""
        raise NotImplementedError()

    def stream(
        self,
        query: UserMessagePromotable,
        *,
        ctx: Context[DepsT] | None = None,
    ) -> StreamResponse[FormatT] | StreamResponse[FormatT]:
        """Streams the response generated by running the agent loop."""
        raise NotImplementedError()


@dataclass
class AsyncAgent(BaseAgent[DepsT, FormatT]):
    """Asynchronous agent class for generating responses using LLMs with tools."""

    async def __call__(
        self,
        query: UserMessagePromotable,
        *,
        ctx: Context[DepsT] | None = None,
    ) -> Response[FormatT]:
        """Generates a response by running the agent loop asynchronously."""
        raise NotImplementedError()

    async def call(
        self,
        query: UserMessagePromotable,
        *,
        ctx: Context[DepsT] | None = None,
    ) -> Response[FormatT]:
        """Generates a response by running the agent loop asynchronously."""
        raise NotImplementedError()

    async def stream(
        self,
        query: UserMessagePromotable,
        *,
        ctx: Context[DepsT] | None = None,
    ) -> AsyncStreamResponse[FormatT] | AsyncStreamResponse[FormatT]:
        """Streams the response generated by running the agent loop asynchronously."""
        raise NotImplementedError()
