"""The `Agent` class for LLM agents."""

from collections.abc import Sequence
from dataclasses import dataclass
from typing import overload

from ..content import UserContent
from ..context import Context, DepsT
from ..response_formatting import FormatT
from ..responses import Response
from ..streams import AsyncStream, Stream
from .base_agent import BaseAgent


@dataclass
class Agent(BaseAgent[DepsT, FormatT]):
    """Agent class for generating responses using LLMs with tools."""

    @overload
    def __call__(
        self: "Agent[None, FormatT]",
        query: UserContent | Sequence[UserContent],
    ) -> Response[None, FormatT]: ...

    @overload
    def __call__(
        self,
        query: UserContent | Sequence[UserContent],
        *,
        ctx: Context[DepsT],
    ) -> Response[DepsT, FormatT]: ...

    def __call__(
        self,
        query: UserContent | Sequence[UserContent],
        *,
        ctx: Context[DepsT] | None = None,
    ) -> Response[DepsT, FormatT] | Response[None, FormatT]:
        """Generates a response by running the agent loop."""
        raise NotImplementedError()

    @overload
    async def run_async(
        self: "Agent[None, FormatT]",
        query: UserContent | Sequence[UserContent],
    ) -> Response[None, FormatT]: ...

    @overload
    async def run_async(
        self,
        query: UserContent | Sequence[UserContent],
        *,
        ctx: Context[DepsT],
    ) -> Response[DepsT, FormatT]: ...

    async def run_async(
        self,
        query: UserContent | Sequence[UserContent],
        *,
        ctx: Context[DepsT] | None = None,
    ) -> Response[DepsT, FormatT] | Response[None, FormatT]:
        """Generates a response by running the agent loop asynchronously."""
        raise NotImplementedError()

    @overload
    def stream(
        self: "Agent[None, FormatT]",
        query: UserContent | Sequence[UserContent],
    ) -> Stream[None, FormatT]: ...

    @overload
    def stream(
        self,
        query: UserContent | Sequence[UserContent],
        *,
        ctx: Context[DepsT],
    ) -> Stream[DepsT, FormatT]: ...

    def stream(
        self,
        query: UserContent | Sequence[UserContent],
        *,
        ctx: Context[DepsT] | None = None,
    ) -> Stream[DepsT, FormatT] | Stream[None, FormatT]:
        """Streams the response generated by running the agent loop."""
        raise NotImplementedError()

    @overload
    async def stream_async(
        self: "Agent[None, FormatT]",
        query: UserContent | Sequence[UserContent],
    ) -> AsyncStream[None, FormatT]: ...

    @overload
    async def stream_async(
        self,
        query: UserContent | Sequence[UserContent],
        *,
        ctx: Context[DepsT],
    ) -> AsyncStream[DepsT, FormatT]: ...

    async def stream_async(
        self,
        query: UserContent | Sequence[UserContent],
        *,
        ctx: Context[DepsT] | None = None,
    ) -> AsyncStream[DepsT, FormatT] | AsyncStream[None, FormatT]:
        """Streams the response generated by running the agent loop asynchronously."""
        raise NotImplementedError()
