repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        exclude: "docs/tutorials/more_advanced/knowledge_graph.ipynb|docs/tutorials/evals/evaluating_web_search_agent.ipynb|docs/tutorials/agents/web_search_agent.ipynb|docs/blog/posts/llm-prompt.md"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.7"
    hooks:
      - id: ruff
        files: "^mirascope|^tests|^examples|^docs"
        args: [--fix]
      - id: ruff-format
        files: "^mirascope|^tests|^examples|^docs"
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.396
    hooks:
      - id: pyright
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: uv run pytest tests
        language: system
        types: [python]
        pass_filenames: false
