// This file was auto-generated by Fern from our API Definition.

import type {
  BaseClientOptions,
  BaseRequestOptions,
} from "../../../../BaseClient.js";

import {
  type NormalizedClientOptions,
  normalizeClientOptions,
} from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import * as Mirascope from "../../../index.js";

export declare namespace AnnotationsClient {
  export type Options = BaseClientOptions;

  export interface RequestOptions extends BaseRequestOptions {}
}

export class AnnotationsClient {
  protected readonly _options: NormalizedClientOptions<AnnotationsClient.Options>;

  constructor(options: AnnotationsClient.Options = {}) {
    this._options = normalizeClientOptions(options);
  }

  /**
   * @param {Mirascope.AnnotationsListRequest} request
   * @param {AnnotationsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link Mirascope.BadRequestError}
   * @throws {@link Mirascope.UnauthorizedError}
   * @throws {@link Mirascope.ForbiddenError}
   * @throws {@link Mirascope.NotFoundError}
   * @throws {@link Mirascope.TooManyRequestsError}
   * @throws {@link Mirascope.InternalServerError}
   * @throws {@link Mirascope.ServiceUnavailableError}
   *
   * @example
   *     await client.annotations.list()
   */
  public list(
    request: Mirascope.AnnotationsListRequest = {},
    requestOptions?: AnnotationsClient.RequestOptions,
  ): core.HttpResponsePromise<Mirascope.AnnotationsListResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__list(request, requestOptions),
    );
  }

  private async __list(
    request: Mirascope.AnnotationsListRequest = {},
    requestOptions?: AnnotationsClient.RequestOptions,
  ): Promise<core.WithRawResponse<Mirascope.AnnotationsListResponse>> {
    const { otelTraceId, otelSpanId, label, limit, offset } = request;
    const _queryParams: Record<string, unknown> = {
      otelTraceId,
      otelSpanId,
      label:
        label != null
          ? serializers.AnnotationsListRequestLabel.jsonOrThrow(label, {
              unrecognizedObjectKeys: "strip",
              omitUndefined: true,
            })
          : undefined,
      limit,
      offset,
    };
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.MirascopeEnvironment.Production,
        "annotations",
      ),
      method: "GET",
      headers: _headers,
      queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
      timeoutMs:
        (requestOptions?.timeoutInSeconds ??
          this._options?.timeoutInSeconds ??
          180) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: serializers.AnnotationsListResponse.parseOrThrow(_response.body, {
          unrecognizedObjectKeys: "passthrough",
          allowUnrecognizedUnionMembers: true,
          allowUnrecognizedEnumValues: true,
          skipValidation: true,
          breadcrumbsPrefix: ["response"],
        }),
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new Mirascope.BadRequestError(
            _response.error.body,
            _response.rawResponse,
          );
        case 401:
          throw new Mirascope.UnauthorizedError(
            serializers.UnauthorizedErrorBody.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 403:
          throw new Mirascope.ForbiddenError(
            serializers.PermissionDeniedError.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 404:
          throw new Mirascope.NotFoundError(
            serializers.NotFoundErrorBody.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 429:
          throw new Mirascope.TooManyRequestsError(
            serializers.RateLimitError.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 500:
          throw new Mirascope.InternalServerError(
            _response.error.body,
            _response.rawResponse,
          );
        case 503:
          throw new Mirascope.ServiceUnavailableError(
            _response.error.body,
            _response.rawResponse,
          );
        default:
          throw new errors.MirascopeError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "GET",
      "/annotations",
    );
  }

  /**
   * @param {Mirascope.AnnotationsCreateRequest} request
   * @param {AnnotationsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link Mirascope.BadRequestError}
   * @throws {@link Mirascope.UnauthorizedError}
   * @throws {@link Mirascope.ForbiddenError}
   * @throws {@link Mirascope.NotFoundError}
   * @throws {@link Mirascope.ConflictError}
   * @throws {@link Mirascope.TooManyRequestsError}
   * @throws {@link Mirascope.InternalServerError}
   * @throws {@link Mirascope.ServiceUnavailableError}
   *
   * @example
   *     await client.annotations.create({
   *         otelSpanId: "otelSpanId",
   *         otelTraceId: "otelTraceId"
   *     })
   */
  public create(
    request: Mirascope.AnnotationsCreateRequest,
    requestOptions?: AnnotationsClient.RequestOptions,
  ): core.HttpResponsePromise<Mirascope.AnnotationsCreateResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__create(request, requestOptions),
    );
  }

  private async __create(
    request: Mirascope.AnnotationsCreateRequest,
    requestOptions?: AnnotationsClient.RequestOptions,
  ): Promise<core.WithRawResponse<Mirascope.AnnotationsCreateResponse>> {
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.MirascopeEnvironment.Production,
        "annotations",
      ),
      method: "POST",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: serializers.AnnotationsCreateRequest.jsonOrThrow(request, {
        unrecognizedObjectKeys: "strip",
        omitUndefined: true,
      }),
      timeoutMs:
        (requestOptions?.timeoutInSeconds ??
          this._options?.timeoutInSeconds ??
          180) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: serializers.AnnotationsCreateResponse.parseOrThrow(
          _response.body,
          {
            unrecognizedObjectKeys: "passthrough",
            allowUnrecognizedUnionMembers: true,
            allowUnrecognizedEnumValues: true,
            skipValidation: true,
            breadcrumbsPrefix: ["response"],
          },
        ),
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new Mirascope.BadRequestError(
            _response.error.body,
            _response.rawResponse,
          );
        case 401:
          throw new Mirascope.UnauthorizedError(
            serializers.UnauthorizedErrorBody.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 403:
          throw new Mirascope.ForbiddenError(
            serializers.PermissionDeniedError.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 404:
          throw new Mirascope.NotFoundError(
            serializers.NotFoundErrorBody.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 409:
          throw new Mirascope.ConflictError(
            _response.error.body,
            _response.rawResponse,
          );
        case 429:
          throw new Mirascope.TooManyRequestsError(
            serializers.RateLimitError.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 500:
          throw new Mirascope.InternalServerError(
            _response.error.body,
            _response.rawResponse,
          );
        case 503:
          throw new Mirascope.ServiceUnavailableError(
            _response.error.body,
            _response.rawResponse,
          );
        default:
          throw new errors.MirascopeError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "POST",
      "/annotations",
    );
  }

  /**
   * @param {Mirascope.AnnotationsGetRequest} request
   * @param {AnnotationsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link Mirascope.BadRequestError}
   * @throws {@link Mirascope.UnauthorizedError}
   * @throws {@link Mirascope.ForbiddenError}
   * @throws {@link Mirascope.NotFoundError}
   * @throws {@link Mirascope.TooManyRequestsError}
   * @throws {@link Mirascope.InternalServerError}
   * @throws {@link Mirascope.ServiceUnavailableError}
   *
   * @example
   *     await client.annotations.get({
   *         id: "id"
   *     })
   */
  public get(
    request: Mirascope.AnnotationsGetRequest,
    requestOptions?: AnnotationsClient.RequestOptions,
  ): core.HttpResponsePromise<Mirascope.AnnotationsGetResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__get(request, requestOptions),
    );
  }

  private async __get(
    request: Mirascope.AnnotationsGetRequest,
    requestOptions?: AnnotationsClient.RequestOptions,
  ): Promise<core.WithRawResponse<Mirascope.AnnotationsGetResponse>> {
    const { id } = request;
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.MirascopeEnvironment.Production,
        `annotations/${core.url.encodePathParam(id)}`,
      ),
      method: "GET",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        (requestOptions?.timeoutInSeconds ??
          this._options?.timeoutInSeconds ??
          180) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: serializers.AnnotationsGetResponse.parseOrThrow(_response.body, {
          unrecognizedObjectKeys: "passthrough",
          allowUnrecognizedUnionMembers: true,
          allowUnrecognizedEnumValues: true,
          skipValidation: true,
          breadcrumbsPrefix: ["response"],
        }),
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new Mirascope.BadRequestError(
            _response.error.body,
            _response.rawResponse,
          );
        case 401:
          throw new Mirascope.UnauthorizedError(
            serializers.UnauthorizedErrorBody.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 403:
          throw new Mirascope.ForbiddenError(
            serializers.PermissionDeniedError.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 404:
          throw new Mirascope.NotFoundError(
            serializers.NotFoundErrorBody.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 429:
          throw new Mirascope.TooManyRequestsError(
            serializers.RateLimitError.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 500:
          throw new Mirascope.InternalServerError(
            _response.error.body,
            _response.rawResponse,
          );
        case 503:
          throw new Mirascope.ServiceUnavailableError(
            _response.error.body,
            _response.rawResponse,
          );
        default:
          throw new errors.MirascopeError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "GET",
      "/annotations/{id}",
    );
  }

  /**
   * @param {Mirascope.AnnotationsUpdateRequest} request
   * @param {AnnotationsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link Mirascope.BadRequestError}
   * @throws {@link Mirascope.UnauthorizedError}
   * @throws {@link Mirascope.ForbiddenError}
   * @throws {@link Mirascope.NotFoundError}
   * @throws {@link Mirascope.TooManyRequestsError}
   * @throws {@link Mirascope.InternalServerError}
   * @throws {@link Mirascope.ServiceUnavailableError}
   *
   * @example
   *     await client.annotations.update({
   *         id: "id"
   *     })
   */
  public update(
    request: Mirascope.AnnotationsUpdateRequest,
    requestOptions?: AnnotationsClient.RequestOptions,
  ): core.HttpResponsePromise<Mirascope.AnnotationsUpdateResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__update(request, requestOptions),
    );
  }

  private async __update(
    request: Mirascope.AnnotationsUpdateRequest,
    requestOptions?: AnnotationsClient.RequestOptions,
  ): Promise<core.WithRawResponse<Mirascope.AnnotationsUpdateResponse>> {
    const { id, ..._body } = request;
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.MirascopeEnvironment.Production,
        `annotations/${core.url.encodePathParam(id)}`,
      ),
      method: "PUT",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: serializers.AnnotationsUpdateRequest.jsonOrThrow(_body, {
        unrecognizedObjectKeys: "strip",
        omitUndefined: true,
      }),
      timeoutMs:
        (requestOptions?.timeoutInSeconds ??
          this._options?.timeoutInSeconds ??
          180) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: serializers.AnnotationsUpdateResponse.parseOrThrow(
          _response.body,
          {
            unrecognizedObjectKeys: "passthrough",
            allowUnrecognizedUnionMembers: true,
            allowUnrecognizedEnumValues: true,
            skipValidation: true,
            breadcrumbsPrefix: ["response"],
          },
        ),
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new Mirascope.BadRequestError(
            _response.error.body,
            _response.rawResponse,
          );
        case 401:
          throw new Mirascope.UnauthorizedError(
            serializers.UnauthorizedErrorBody.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 403:
          throw new Mirascope.ForbiddenError(
            serializers.PermissionDeniedError.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 404:
          throw new Mirascope.NotFoundError(
            serializers.NotFoundErrorBody.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 429:
          throw new Mirascope.TooManyRequestsError(
            serializers.RateLimitError.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 500:
          throw new Mirascope.InternalServerError(
            _response.error.body,
            _response.rawResponse,
          );
        case 503:
          throw new Mirascope.ServiceUnavailableError(
            _response.error.body,
            _response.rawResponse,
          );
        default:
          throw new errors.MirascopeError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "PUT",
      "/annotations/{id}",
    );
  }

  /**
   * @param {Mirascope.AnnotationsDeleteRequest} request
   * @param {AnnotationsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link Mirascope.BadRequestError}
   * @throws {@link Mirascope.UnauthorizedError}
   * @throws {@link Mirascope.ForbiddenError}
   * @throws {@link Mirascope.NotFoundError}
   * @throws {@link Mirascope.TooManyRequestsError}
   * @throws {@link Mirascope.InternalServerError}
   * @throws {@link Mirascope.ServiceUnavailableError}
   *
   * @example
   *     await client.annotations.delete({
   *         id: "id"
   *     })
   */
  public delete(
    request: Mirascope.AnnotationsDeleteRequest,
    requestOptions?: AnnotationsClient.RequestOptions,
  ): core.HttpResponsePromise<void> {
    return core.HttpResponsePromise.fromPromise(
      this.__delete(request, requestOptions),
    );
  }

  private async __delete(
    request: Mirascope.AnnotationsDeleteRequest,
    requestOptions?: AnnotationsClient.RequestOptions,
  ): Promise<core.WithRawResponse<void>> {
    const { id } = request;
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.MirascopeEnvironment.Production,
        `annotations/${core.url.encodePathParam(id)}`,
      ),
      method: "DELETE",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        (requestOptions?.timeoutInSeconds ??
          this._options?.timeoutInSeconds ??
          180) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return { data: undefined, rawResponse: _response.rawResponse };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new Mirascope.BadRequestError(
            _response.error.body,
            _response.rawResponse,
          );
        case 401:
          throw new Mirascope.UnauthorizedError(
            serializers.UnauthorizedErrorBody.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 403:
          throw new Mirascope.ForbiddenError(
            serializers.PermissionDeniedError.parseOrThrow(
              _response.error.body,
              {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
              },
            ),
            _response.rawResponse,
          );
        case 404:
          throw new Mirascope.NotFoundError(
            serializers.NotFoundErrorBody.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 429:
          throw new Mirascope.TooManyRequestsError(
            serializers.RateLimitError.parseOrThrow(_response.error.body, {
              unrecognizedObjectKeys: "passthrough",
              allowUnrecognizedUnionMembers: true,
              allowUnrecognizedEnumValues: true,
              skipValidation: true,
              breadcrumbsPrefix: ["response"],
            }),
            _response.rawResponse,
          );
        case 500:
          throw new Mirascope.InternalServerError(
            _response.error.body,
            _response.rawResponse,
          );
        case 503:
          throw new Mirascope.ServiceUnavailableError(
            _response.error.body,
            _response.rawResponse,
          );
        default:
          throw new errors.MirascopeError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "DELETE",
      "/annotations/{id}",
    );
  }
}
