// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         projectId: "projectId",
 *         name: "name",
 *         slug: "slug"
 *     }
 */
export interface EnvironmentsCreateRequest {
  organizationId: string;
  projectId: string;
  /** a string at most 100 character(s) long */
  name: string;
  /** a string matching the pattern ^[a-z0-9][a-z0-9_-]*[a-z0-9]$ */
  slug: string;
}
