/**
 * @fileoverview Interface for LLM responses.
 * 
 * This module defines interfaces for the responses returned by language models,
 * including methods for formatting the response according to a specified format.
 */

import { BaseResponse } from "./base-response";
import type { ResponseContent } from "./content";

/**
 * The response generated by an LLM.
 */
export class Response<T extends object | null = null> extends BaseResponse<
  ResponseContent,
  T
> {}
