// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../index.js";

/**
 * @example
 *     {
 *         provider: "provider",
 *         model: "model",
 *         usage: {
 *             inputTokens: 1.1,
 *             outputTokens: 1.1
 *         }
 *     }
 */
export interface TokenCostCalculateRequest {
  /** a non empty string */
  provider: string;
  /** a non empty string */
  model: string;
  usage: Mirascope.TokenCostCalculateRequestUsage;
  viaRouter?: boolean;
}
