// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         targetPlan: "free"
 *     }
 */
export interface OrganizationsUpdateSubscriptionRequest {
  id: string;
  targetPlan: Mirascope.OrganizationsUpdateSubscriptionRequestTargetPlan;
}
