# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.api_error import ApiError
from ..types.already_exists_error import AlreadyExistsError


class ConflictError(ApiError):
    def __init__(
        self,
        body: AlreadyExistsError,
        headers: typing.Optional[typing.Dict[str, str]] = None,
    ):
        super().__init__(status_code=409, headers=headers, body=body)
