/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseRouteImport } from './routes/use'
import { Route as SocialCardRouteImport } from './routes/social-card'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as RouterWaitlistRouteImport } from './routes/router-waitlist'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsFullRouteImport } from './routes/llms-full'
import { Route as LayoutTestRouteImport } from './routes/layout-test'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AuditMetadataRouteImport } from './routes/audit-metadata'
import { Route as R404RouteImport } from './routes/404'
import { Route as CatchallRouteImport } from './routes/$catchall'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as DevSlugRouteImport } from './routes/dev.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthMeRouteImport } from './routes/auth/me'
import { Route as AuthGoogleRouteImport } from './routes/auth/google'
import { Route as AuthGithubRouteImport } from './routes/auth/github'
import { Route as DocsProductLlmsFullRouteImport } from './routes/docs.$product.llms-full'
import { Route as AuthGoogleProxyCallbackRouteImport } from './routes/auth/google.proxy-callback'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google.callback'
import { Route as AuthGithubProxyCallbackRouteImport } from './routes/auth/github.proxy-callback'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth/github.callback'
import { Route as ApiV0HealthRouteImport } from './routes/api.v0.health'
import { Route as ApiV0DocsRouteImport } from './routes/api.v0.docs'
import { Route as ApiV0SplatRouteImport } from './routes/api.v0.$'
import { Route as DocsMirascopeV2LlmsFullRouteImport } from './routes/docs.mirascope.v2.llms-full'

const UseRoute = UseRouteImport.update({
  id: '/use',
  path: '/use',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialCardRoute = SocialCardRouteImport.update({
  id: '/social-card',
  path: '/social-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const RouterWaitlistRoute = RouterWaitlistRouteImport.update({
  id: '/router-waitlist',
  path: '/router-waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullRoute = LlmsFullRouteImport.update({
  id: '/llms-full',
  path: '/llms-full',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTestRoute = LayoutTestRouteImport.update({
  id: '/layout-test',
  path: '/layout-test',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditMetadataRoute = AuditMetadataRouteImport.update({
  id: '/audit-metadata',
  path: '/audit-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const CatchallRoute = CatchallRouteImport.update({
  id: '/$catchall',
  path: '/$catchall',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSlugRoute = DevSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DevRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMeRoute = AuthMeRouteImport.update({
  id: '/auth/me',
  path: '/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubRoute = AuthGithubRouteImport.update({
  id: '/auth/github',
  path: '/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsProductLlmsFullRoute = DocsProductLlmsFullRouteImport.update({
  id: '/docs/$product/llms-full',
  path: '/docs/$product/llms-full',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleProxyCallbackRoute = AuthGoogleProxyCallbackRouteImport.update({
  id: '/proxy-callback',
  path: '/proxy-callback',
  getParentRoute: () => AuthGoogleRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthGoogleRoute,
} as any)
const AuthGithubProxyCallbackRoute = AuthGithubProxyCallbackRouteImport.update({
  id: '/proxy-callback',
  path: '/proxy-callback',
  getParentRoute: () => AuthGithubRoute,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthGithubRoute,
} as any)
const ApiV0HealthRoute = ApiV0HealthRouteImport.update({
  id: '/api/v0/health',
  path: '/api/v0/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV0DocsRoute = ApiV0DocsRouteImport.update({
  id: '/api/v0/docs',
  path: '/api/v0/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV0SplatRoute = ApiV0SplatRouteImport.update({
  id: '/api/v0/$',
  path: '/api/v0/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMirascopeV2LlmsFullRoute = DocsMirascopeV2LlmsFullRouteImport.update({
  id: '/docs/mirascope/v2/llms-full',
  path: '/docs/mirascope/v2/llms-full',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$catchall': typeof CatchallRoute
  '/404': typeof R404Route
  '/audit-metadata': typeof AuditMetadataRoute
  '/dev': typeof DevRouteWithChildren
  '/home': typeof HomeRoute
  '/layout-test': typeof LayoutTestRoute
  '/llms-full': typeof LlmsFullRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/router-waitlist': typeof RouterWaitlistRoute
  '/service': typeof ServiceRoute
  '/social-card': typeof SocialCardRoute
  '/use': typeof UseRoute
  '/auth/github': typeof AuthGithubRouteWithChildren
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/me': typeof AuthMeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dev/$slug': typeof DevSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/v0/$': typeof ApiV0SplatRoute
  '/api/v0/docs': typeof ApiV0DocsRoute
  '/api/v0/health': typeof ApiV0HealthRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/auth/github/proxy-callback': typeof AuthGithubProxyCallbackRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/proxy-callback': typeof AuthGoogleProxyCallbackRoute
  '/docs/$product/llms-full': typeof DocsProductLlmsFullRoute
  '/docs/mirascope/v2/llms-full': typeof DocsMirascopeV2LlmsFullRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$catchall': typeof CatchallRoute
  '/404': typeof R404Route
  '/audit-metadata': typeof AuditMetadataRoute
  '/dev': typeof DevRouteWithChildren
  '/home': typeof HomeRoute
  '/layout-test': typeof LayoutTestRoute
  '/llms-full': typeof LlmsFullRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/router-waitlist': typeof RouterWaitlistRoute
  '/service': typeof ServiceRoute
  '/social-card': typeof SocialCardRoute
  '/use': typeof UseRoute
  '/auth/github': typeof AuthGithubRouteWithChildren
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/me': typeof AuthMeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dev/$slug': typeof DevSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/v0/$': typeof ApiV0SplatRoute
  '/api/v0/docs': typeof ApiV0DocsRoute
  '/api/v0/health': typeof ApiV0HealthRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/auth/github/proxy-callback': typeof AuthGithubProxyCallbackRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/proxy-callback': typeof AuthGoogleProxyCallbackRoute
  '/docs/$product/llms-full': typeof DocsProductLlmsFullRoute
  '/docs/mirascope/v2/llms-full': typeof DocsMirascopeV2LlmsFullRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$catchall': typeof CatchallRoute
  '/404': typeof R404Route
  '/audit-metadata': typeof AuditMetadataRoute
  '/dev': typeof DevRouteWithChildren
  '/home': typeof HomeRoute
  '/layout-test': typeof LayoutTestRoute
  '/llms-full': typeof LlmsFullRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/router-waitlist': typeof RouterWaitlistRoute
  '/service': typeof ServiceRoute
  '/social-card': typeof SocialCardRoute
  '/use': typeof UseRoute
  '/auth/github': typeof AuthGithubRouteWithChildren
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/me': typeof AuthMeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dev/$slug': typeof DevSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/v0/$': typeof ApiV0SplatRoute
  '/api/v0/docs': typeof ApiV0DocsRoute
  '/api/v0/health': typeof ApiV0HealthRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/auth/github/proxy-callback': typeof AuthGithubProxyCallbackRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/proxy-callback': typeof AuthGoogleProxyCallbackRoute
  '/docs/$product/llms-full': typeof DocsProductLlmsFullRoute
  '/docs/mirascope/v2/llms-full': typeof DocsMirascopeV2LlmsFullRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$catchall'
    | '/404'
    | '/audit-metadata'
    | '/dev'
    | '/home'
    | '/layout-test'
    | '/llms-full'
    | '/login'
    | '/organizations'
    | '/pricing'
    | '/privacy'
    | '/router-waitlist'
    | '/service'
    | '/social-card'
    | '/use'
    | '/auth/github'
    | '/auth/google'
    | '/auth/me'
    | '/blog/$slug'
    | '/dev/$slug'
    | '/docs/$'
    | '/blog'
    | '/docs'
    | '/api/v0/$'
    | '/api/v0/docs'
    | '/api/v0/health'
    | '/auth/github/callback'
    | '/auth/github/proxy-callback'
    | '/auth/google/callback'
    | '/auth/google/proxy-callback'
    | '/docs/$product/llms-full'
    | '/docs/mirascope/v2/llms-full'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$catchall'
    | '/404'
    | '/audit-metadata'
    | '/dev'
    | '/home'
    | '/layout-test'
    | '/llms-full'
    | '/login'
    | '/organizations'
    | '/pricing'
    | '/privacy'
    | '/router-waitlist'
    | '/service'
    | '/social-card'
    | '/use'
    | '/auth/github'
    | '/auth/google'
    | '/auth/me'
    | '/blog/$slug'
    | '/dev/$slug'
    | '/docs/$'
    | '/blog'
    | '/docs'
    | '/api/v0/$'
    | '/api/v0/docs'
    | '/api/v0/health'
    | '/auth/github/callback'
    | '/auth/github/proxy-callback'
    | '/auth/google/callback'
    | '/auth/google/proxy-callback'
    | '/docs/$product/llms-full'
    | '/docs/mirascope/v2/llms-full'
  id:
    | '__root__'
    | '/'
    | '/$catchall'
    | '/404'
    | '/audit-metadata'
    | '/dev'
    | '/home'
    | '/layout-test'
    | '/llms-full'
    | '/login'
    | '/organizations'
    | '/pricing'
    | '/privacy'
    | '/router-waitlist'
    | '/service'
    | '/social-card'
    | '/use'
    | '/auth/github'
    | '/auth/google'
    | '/auth/me'
    | '/blog/$slug'
    | '/dev/$slug'
    | '/docs/$'
    | '/blog/'
    | '/docs/'
    | '/api/v0/$'
    | '/api/v0/docs'
    | '/api/v0/health'
    | '/auth/github/callback'
    | '/auth/github/proxy-callback'
    | '/auth/google/callback'
    | '/auth/google/proxy-callback'
    | '/docs/$product/llms-full'
    | '/docs/mirascope/v2/llms-full'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatchallRoute: typeof CatchallRoute
  R404Route: typeof R404Route
  AuditMetadataRoute: typeof AuditMetadataRoute
  DevRoute: typeof DevRouteWithChildren
  HomeRoute: typeof HomeRoute
  LayoutTestRoute: typeof LayoutTestRoute
  LlmsFullRoute: typeof LlmsFullRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RouterWaitlistRoute: typeof RouterWaitlistRoute
  ServiceRoute: typeof ServiceRoute
  SocialCardRoute: typeof SocialCardRoute
  UseRoute: typeof UseRoute
  AuthGithubRoute: typeof AuthGithubRouteWithChildren
  AuthGoogleRoute: typeof AuthGoogleRouteWithChildren
  AuthMeRoute: typeof AuthMeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DocsSplatRoute: typeof DocsSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiV0SplatRoute: typeof ApiV0SplatRoute
  ApiV0DocsRoute: typeof ApiV0DocsRoute
  ApiV0HealthRoute: typeof ApiV0HealthRoute
  DocsProductLlmsFullRoute: typeof DocsProductLlmsFullRoute
  DocsMirascopeV2LlmsFullRoute: typeof DocsMirascopeV2LlmsFullRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use': {
      id: '/use'
      path: '/use'
      fullPath: '/use'
      preLoaderRoute: typeof UseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-card': {
      id: '/social-card'
      path: '/social-card'
      fullPath: '/social-card'
      preLoaderRoute: typeof SocialCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/router-waitlist': {
      id: '/router-waitlist'
      path: '/router-waitlist'
      fullPath: '/router-waitlist'
      preLoaderRoute: typeof RouterWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full': {
      id: '/llms-full'
      path: '/llms-full'
      fullPath: '/llms-full'
      preLoaderRoute: typeof LlmsFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout-test': {
      id: '/layout-test'
      path: '/layout-test'
      fullPath: '/layout-test'
      preLoaderRoute: typeof LayoutTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-metadata': {
      id: '/audit-metadata'
      path: '/audit-metadata'
      fullPath: '/audit-metadata'
      preLoaderRoute: typeof AuditMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$catchall': {
      id: '/$catchall'
      path: '/$catchall'
      fullPath: '/$catchall'
      preLoaderRoute: typeof CatchallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/$slug': {
      id: '/dev/$slug'
      path: '/$slug'
      fullPath: '/dev/$slug'
      preLoaderRoute: typeof DevSlugRouteImport
      parentRoute: typeof DevRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/me': {
      id: '/auth/me'
      path: '/auth/me'
      fullPath: '/auth/me'
      preLoaderRoute: typeof AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github': {
      id: '/auth/github'
      path: '/auth/github'
      fullPath: '/auth/github'
      preLoaderRoute: typeof AuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$product/llms-full': {
      id: '/docs/$product/llms-full'
      path: '/docs/$product/llms-full'
      fullPath: '/docs/$product/llms-full'
      preLoaderRoute: typeof DocsProductLlmsFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/proxy-callback': {
      id: '/auth/google/proxy-callback'
      path: '/proxy-callback'
      fullPath: '/auth/google/proxy-callback'
      preLoaderRoute: typeof AuthGoogleProxyCallbackRouteImport
      parentRoute: typeof AuthGoogleRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthGoogleRoute
    }
    '/auth/github/proxy-callback': {
      id: '/auth/github/proxy-callback'
      path: '/proxy-callback'
      fullPath: '/auth/github/proxy-callback'
      preLoaderRoute: typeof AuthGithubProxyCallbackRouteImport
      parentRoute: typeof AuthGithubRoute
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof AuthGithubRoute
    }
    '/api/v0/health': {
      id: '/api/v0/health'
      path: '/api/v0/health'
      fullPath: '/api/v0/health'
      preLoaderRoute: typeof ApiV0HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v0/docs': {
      id: '/api/v0/docs'
      path: '/api/v0/docs'
      fullPath: '/api/v0/docs'
      preLoaderRoute: typeof ApiV0DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v0/$': {
      id: '/api/v0/$'
      path: '/api/v0/$'
      fullPath: '/api/v0/$'
      preLoaderRoute: typeof ApiV0SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/mirascope/v2/llms-full': {
      id: '/docs/mirascope/v2/llms-full'
      path: '/docs/mirascope/v2/llms-full'
      fullPath: '/docs/mirascope/v2/llms-full'
      preLoaderRoute: typeof DocsMirascopeV2LlmsFullRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DevRouteChildren {
  DevSlugRoute: typeof DevSlugRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevSlugRoute: DevSlugRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

interface AuthGithubRouteChildren {
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
  AuthGithubProxyCallbackRoute: typeof AuthGithubProxyCallbackRoute
}

const AuthGithubRouteChildren: AuthGithubRouteChildren = {
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
  AuthGithubProxyCallbackRoute: AuthGithubProxyCallbackRoute,
}

const AuthGithubRouteWithChildren = AuthGithubRoute._addFileChildren(
  AuthGithubRouteChildren,
)

interface AuthGoogleRouteChildren {
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthGoogleProxyCallbackRoute: typeof AuthGoogleProxyCallbackRoute
}

const AuthGoogleRouteChildren: AuthGoogleRouteChildren = {
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthGoogleProxyCallbackRoute: AuthGoogleProxyCallbackRoute,
}

const AuthGoogleRouteWithChildren = AuthGoogleRoute._addFileChildren(
  AuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatchallRoute: CatchallRoute,
  R404Route: R404Route,
  AuditMetadataRoute: AuditMetadataRoute,
  DevRoute: DevRouteWithChildren,
  HomeRoute: HomeRoute,
  LayoutTestRoute: LayoutTestRoute,
  LlmsFullRoute: LlmsFullRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RouterWaitlistRoute: RouterWaitlistRoute,
  ServiceRoute: ServiceRoute,
  SocialCardRoute: SocialCardRoute,
  UseRoute: UseRoute,
  AuthGithubRoute: AuthGithubRouteWithChildren,
  AuthGoogleRoute: AuthGoogleRouteWithChildren,
  AuthMeRoute: AuthMeRoute,
  BlogSlugRoute: BlogSlugRoute,
  DocsSplatRoute: DocsSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiV0SplatRoute: ApiV0SplatRoute,
  ApiV0DocsRoute: ApiV0DocsRoute,
  ApiV0HealthRoute: ApiV0HealthRoute,
  DocsProductLlmsFullRoute: DocsProductLlmsFullRoute,
  DocsMirascopeV2LlmsFullRoute: DocsMirascopeV2LlmsFullRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
