# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.resource_spans import ResourceSpans
from ..types.trace_response import TraceResponse
from .raw_client import AsyncRawTracesClient, RawTracesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TracesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTracesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTracesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTracesClient
        """
        return self._raw_client

    def create(
        self,
        *,
        resource_spans: typing.Sequence[ResourceSpans],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TraceResponse:
        """
        Temporary endpoint to receive and log OpenTelemetry trace data for debugging purposes. This endpoint follows the OTLP/HTTP specification.

        Parameters
        ----------
        resource_spans : typing.Sequence[ResourceSpans]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TraceResponse
            Trace export acknowledged

        Examples
        --------
        from mirascope._generated import Mirascope, ResourceSpans, ScopeSpans, Span

        client = Mirascope()
        client.traces.create(
            resource_spans=[
                ResourceSpans(
                    scope_spans=[
                        ScopeSpans(
                            spans=[
                                Span(
                                    trace_id="traceId",
                                    span_id="spanId",
                                    name="name",
                                    start_time_unix_nano="startTimeUnixNano",
                                    end_time_unix_nano="endTimeUnixNano",
                                )
                            ],
                        )
                    ],
                )
            ],
        )
        """
        _response = self._raw_client.create(
            resource_spans=resource_spans, request_options=request_options
        )
        return _response.data


class AsyncTracesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTracesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTracesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTracesClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        resource_spans: typing.Sequence[ResourceSpans],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TraceResponse:
        """
        Temporary endpoint to receive and log OpenTelemetry trace data for debugging purposes. This endpoint follows the OTLP/HTTP specification.

        Parameters
        ----------
        resource_spans : typing.Sequence[ResourceSpans]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TraceResponse
            Trace export acknowledged

        Examples
        --------
        import asyncio

        from mirascope._generated import AsyncMirascope, ResourceSpans, ScopeSpans, Span

        client = AsyncMirascope()


        async def main() -> None:
            await client.traces.create(
                resource_spans=[
                    ResourceSpans(
                        scope_spans=[
                            ScopeSpans(
                                spans=[
                                    Span(
                                        trace_id="traceId",
                                        span_id="spanId",
                                        name="name",
                                        start_time_unix_nano="startTimeUnixNano",
                                        end_time_unix_nano="endTimeUnixNano",
                                    )
                                ],
                            )
                        ],
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            resource_spans=resource_spans, request_options=request_options
        )
        return _response.data
