// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../../api/index.js";
import type * as serializers from "../../../../index.js";

import * as core from "../../../../../core/index.js";

export const OrganizationsCreateRequest: core.serialization.Schema<
  serializers.OrganizationsCreateRequest.Raw,
  Mirascope.OrganizationsCreateRequest
> = core.serialization.object({
  name: core.serialization.string(),
  slug: core.serialization.string(),
});

export declare namespace OrganizationsCreateRequest {
  export interface Raw {
    name: string;
    slug: string;
  }
}
