/**
 * @fileoverview Slug generation utilities for URL-safe identifiers.
 *
 * Provides utilities for generating slugs from display names. Slugs are
 * normalized, URL-safe identifiers used for uniqueness constraints.
 *
 * @example
 * ```ts
 * const slug = generateSlug("Mirascope, Inc.");
 * // Returns: "mirascope-inc"
 * ```
 */

import { Schema } from "effect";

/**
 * Organization slugs that are reserved to prevent conflicts with routes,
 * infrastructure, redirects, and common abuse vectors.
 *
 * Strings that fail slug validation (< 3 chars, non-alphanumeric start/end)
 * are naturally blocked and don't need to be listed here (e.g. "ws", "_", "-").
 */
export const RESERVED_ORG_SLUGS: ReadonlySet<string> = new Set([
  // Infrastructure subdomains
  "claws", // internal container addressing: *.claws.mirascope.com
  "staging", // staging.mirascope.com
  "www", // standard web subdomain
  "api", // future API subdomain
  "internal", // used by service binding fetch origin
  "app", // common infrastructure subdomain
  "cloud", // cloud.mirascope.com
  "org-redirect", // /org-redirect route
  "docs", // docs.mirascope.com
  "admin", // common infrastructure subdomain
  "mail", // common infrastructure subdomain
  "cdn",
  "static",
  "assets",
  "status",
  "health",
  "graphql",
  "webhooks",
  "metrics",

  // Top-level static routes (conflict with $orgSlug dynamic segment)
  "blog",
  "dev",
  "organizations",
  "pricing",
  "privacy",
  "auth",
  "invitations",
  "terms",
  "router",
  "login",
  "onboarding",
  "agents",

  // Server-level redirects (handled by redirects.ts before TanStack Router)
  "discord-invite",
  "slack-invite",
  "post",
  "integrations",

  // Auth / account flows
  "signup",
  "register",
  "logout",
  "callback",
  "oauth",
  "sso",
  "account",
  "settings",
  "profile",
  "verify",
  "reset-password",
  "confirm",

  // Marketing / static pages likely to be added
  "about",
  "careers",
  "jobs",
  "contact",
  "support",
  "help",
  "press",
  "changelog",
  "features",
  "enterprise",
  "teams",
  "home",
  "security",

  // Legal
  "legal",
  "cookies",
  "dmca",
  "compliance",
  "acceptable-use",

  // Product routes that tend to emerge
  "dashboard",
  "console",
  "explore",
  "search",
  "marketplace",
  "billing",
  "checkout",
  "plans",
  "notifications",
  "new",
  "create",
  "feed",

  // Abuse prevention — impersonation of authority
  "administrator",
  "moderator",
  "system",
  "root",
  "info",
  "noreply",
  "abuse",
  "postmaster",
  "webmaster",
  "mirascope",
  "official",
  "team",
  "staff",
  "engineering",

  // Dangerous edge-case strings
  "null",
  "undefined",
  "true",
  "false",
  "test",
  "demo",
  "example",
  "localhost",
]);

/**
 * Returns true if the slug is reserved for infrastructure use and cannot
 * be used as an organization slug.
 */
export function isReservedOrgSlug(slug: string): boolean {
  return RESERVED_ORG_SLUGS.has(slug);
}

/**
 * Generates a URL-safe slug from a given name.
 *
 * The slug is generated by:
 * 1. Converting to lowercase
 * 2. Trimming whitespace
 * 3. Replacing spaces and special characters with hyphens
 * 4. Removing consecutive hyphens
 * 5. Removing leading/trailing hyphens
 *
 * Valid slug characters: a-z, 0-9, hyphens, underscores
 *
 * @param name - The display name to convert to a slug
 * @returns A URL-safe slug
 *
 * @example
 * ```ts
 * generateSlug("Mirascope, Inc.") // "mirascope-inc"
 * generateSlug("My Project Name") // "my-project-name"
 * generateSlug("Test_Environment") // "test_environment"
 * generateSlug("  Spaces  ") // "spaces"
 * ```
 */
export function generateSlug(name: string): string {
  return (
    name
      .toLowerCase()
      .trim()
      // Replace spaces and special characters (except underscores) with hyphens
      .replace(/[^\w]+/g, "-")
      // Remove consecutive hyphens
      .replace(/-+/g, "-")
      // Remove leading/trailing hyphens
      .replace(/^-+|-+$/g, "")
  );
}

/**
 * Validates that a slug only contains allowed characters.
 *
 * Valid slugs must:
 * - Be at least 3 characters long
 * - Start with a letter or number
 * - End with a letter or number
 * - Contain only lowercase letters, numbers, hyphens, and underscores
 *
 * @param slug - The slug to validate
 * @returns True if the slug is valid
 *
 * @example
 * ```ts
 * isValidSlug("my-project") // true
 * isValidSlug("my_project") // true
 * isValidSlug("abc") // true
 * isValidSlug("My-Project") // false (uppercase)
 * isValidSlug("my project") // false (space)
 * isValidSlug("ab") // false (too short)
 * isValidSlug("---") // false (doesn't start/end with alphanumeric)
 * isValidSlug("_a_") // false (doesn't start/end with alphanumeric)
 * isValidSlug("-abc") // false (doesn't start with alphanumeric)
 * isValidSlug("abc-") // false (doesn't end with alphanumeric)
 * ```
 */
export function isValidSlug(slug: string): boolean {
  // Must be at least 3 characters, start and end with alphanumeric,
  // and only contain lowercase letters, numbers, hyphens, and underscores
  return slug.length >= 3 && /^[a-z0-9][a-z0-9_-]*[a-z0-9]$/.test(slug);
}

/**
 * Creates a reusable slug schema for a given resource type.
 *
 * The schema validates that slugs:
 * - Are between 3 and 100 characters
 * - Start and end with a letter or number
 * - Contain only lowercase letters, numbers, hyphens, and underscores
 *
 * @param resourceName - The name of the resource (e.g., "Organization", "Project", "Environment")
 * @returns A Schema.String with slug validation rules
 *
 * @example
 * ```ts
 * const ProjectSlugSchema = createSlugSchema("Project");
 * const EnvironmentSlugSchema = createSlugSchema("Environment");
 * ```
 */
export const createSlugSchema = (resourceName: string) =>
  Schema.String.pipe(
    Schema.minLength(3, {
      message: () => `${resourceName} slug must be at least 3 characters`,
    }),
    Schema.maxLength(100, {
      message: () => `${resourceName} slug must be at most 100 characters`,
    }),
    Schema.pattern(/^[a-z0-9][a-z0-9_-]*[a-z0-9]$/, {
      message: () =>
        `${resourceName} slug must start and end with a letter or number, and only contain lowercase letters, numbers, hyphens, and underscores`,
    }),
  );
