// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../../api/index.js";
import type * as serializers from "../../../../index.js";

import * as core from "../../../../../core/index.js";

export const TagsUpdateRequest: core.serialization.Schema<
  serializers.TagsUpdateRequest.Raw,
  Omit<Mirascope.TagsUpdateRequest, "organizationId" | "projectId" | "tagId">
> = core.serialization.object({
  name: core.serialization.string().optional(),
});

export declare namespace TagsUpdateRequest {
  export interface Raw {
    name?: string | null;
  }
}
