/**
 * ContextResponse class for context-based LLM calls.
 *
 * Extends BaseResponse with context-aware functionality including:
 * - executeTools(): Execute tool calls with context dependency injection
 */

import type { Context } from '@/llm/context';
import {
  BaseResponse,
  type BaseResponseInit,
} from '@/llm/responses/base-response';

/**
 * Initialization options for creating a ContextResponse.
 */
export type ContextResponseInit = BaseResponseInit;

/**
 * The response generated by an LLM from a context call.
 *
 * This class provides context-aware functionality on top of the standard response:
 * - `executeTools()`: Execute all tool calls with context dependency injection
 *
 * @template DepsT - The type of dependencies in the context.
 *
 * @example
 * ```typescript
 * interface MyDeps { userId: string; }
 *
 * const ctx = createContext<MyDeps>({ userId: '123' });
 * const response = await myPrompt(model, ctx);
 * console.log(response.text());
 * ```
 */
export class ContextResponse<DepsT = unknown> extends BaseResponse {
  constructor(init: ContextResponseInit) {
    super(init);
  }

  /* v8 ignore start - tools not yet implemented */
  /**
   * Execute and return all of the tool calls in the response.
   *
   * @param _ctx - A Context with the required deps type.
   * @returns A sequence containing a ToolOutput for every tool call.
   *
   * @throws ToolNotFoundError if one of the response's tool calls has no matching tool.
   * @throws Error if one of the tools throws an exception.
   *
   * @example
   * ```typescript
   * const response = await myPrompt(model, ctx);
   * const outputs = response.executeTools(ctx);
   * for (const output of outputs) {
   *   console.log(output);
   * }
   * ```
   */
  executeTools(_ctx: Context<DepsT>): unknown[] {
    // Note: Tool execution is not yet implemented.
    // When implemented, this will:
    // 1. Iterate through this.toolCalls
    // 2. For each tool call, find the matching tool in the toolkit
    // 3. Execute the tool with the context and tool call arguments
    // 4. Return an array of ToolOutput objects
    return [];
  }
  /* v8 ignore stop */
}
