"""Interfaces for LLM responses.

This module defines interfaces for the responses returned by language models,
including methods for formatting the response according to a specified format.
"""

from collections.abc import Sequence
from typing import Generic

from typing_extensions import Self, TypeVar

from .messages import Message
from .tools import Tool

T = TypeVar("T", default=None)


class Response(Generic[T]):
    """The response generated by an LLM.

    This class represents a complete response from a language model,
    including the generated content, usage statistics, and any tool calls
    that were made during generation.
    """

    content: str
    """The generated text content of the response."""

    message: Message
    """The full message object representing the response."""

    tools: Sequence[Tool]
    """Tool calls that were generated as part of this response."""

    usage: dict[str, int]
    """Token usage statistics for this generation."""

    raw: dict
    """The raw response data from the provider."""

    def format(self) -> T:
        """Format the response according to the response format parser.

        This method is only available if the generation was created with a
        ResponseFormat[T]. It will parse the response content according to
        the specified format and return a structured object.

        Returns:
            The formatted response object of type T.

        Raises:
            ValueError: If the response cannot be formatted according to the
                specified format.
        """
        raise NotImplementedError()

    def to_message(self) -> Message:
        """Convert this response to a message that can be used in a conversation.

        Returns:
            A Message object representing this response.
        """
        raise NotImplementedError()

    @classmethod
    def from_content(cls, content: str) -> Self:
        """Create a simple Response object from content text.

        Args:
            content: The text content to include in the response.

        Returns:
            A new Response object with just the content populated.
        """
        raise NotImplementedError()
