// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../index.js";

/**
 * @example
 *     {
 *         hash: "hash"
 *     }
 */
export interface TracesListByFunctionHashRequest {
  hash: string;
  limit?: Mirascope.NumberFromString;
  offset?: Mirascope.NumberFromString;
}
