"""Interfaces for LLM responses with context.

This module defines interfaces for the responses returned by language models that have
contextual information or data, such as the history of messages used to generate the
response.
"""

from dataclasses import dataclass
from typing import Generic

from typing_extensions import TypeVar

from ..tools import ContextTool
from ..types import Jsonable
from .base_response import BaseResponse
from .content import ContextResponseContent

DepsT = TypeVar("DepsT", default=None)
T = TypeVar("T", bound=object | None, default=None)


@dataclass
class ContextResponse(
    BaseResponse[ContextResponseContent, ContextTool[..., Jsonable, DepsT], T],
    Generic[DepsT, T],
):
    """The response generated by an LLM."""
