"""The `ContextStreamChunk` class for handling streamed chunks from contextual LLM calls."""

from dataclasses import dataclass

from typing_extensions import TypeVar

from ..context import Context
from ..tools import ContextTool
from ..types import Jsonable
from .base_stream_chunk import BaseStreamChunk
from .content import ContextResponseContent

T = TypeVar("T", bound=object | None, default=None)
DepsT = TypeVar("DepsT", default=None)


@dataclass
class ContextStreamChunk(BaseStreamChunk[ContextResponseContent, ContextTool[..., Jsonable, DepsT], T]):
    """A chunk of a streaming response from a contextual LLM call.

    Context stream chunks represent incremental pieces of a response that are delivered
    as they are generated by the model, allowing for real-time display and processing
    with access to the context dependencies.
    """

    ctx: Context[DepsT]
    """The context associated with this stream chunk."""
