"""Concrete LLM response implementation."""

from ..formatting import FormatT
from .base_response import BaseResponse
from .finish_reason import FinishReason


class Response(BaseResponse[FormatT]):
    """The response generated by an LLM."""

    finish_reason: FinishReason | None
    """The reason why the LLM finished generating a response.
    
    Will be None when the response is a StreamResponse that has not finished streaming."""
