"""Concrete LLM response implementation."""

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any

from ..content import Text, Thinking, ToolCall
from ..formatting import FormatT
from ..messages import AssistantMessage, Message
from ..tools import FORMAT_TOOL_NAME
from ..types import NoneType
from .base_response import BaseResponse
from .finish_reason import FinishReason

if TYPE_CHECKING:
    from ..clients import Model, Provider


class Response(BaseResponse[FormatT]):
    """The response generated by an LLM."""

    def __init__(
        self,
        *,
        provider: "Provider",
        model: "Model",
        format: type[FormatT] = NoneType,
        input_messages: Sequence[Message],
        assistant_message: AssistantMessage,
        finish_reason: FinishReason | None,
        raw: Any,  # noqa: ANN401
    ) -> None:
        """Initialize a Response.

        Args:
            model: The model identifier that generated the response.
            input_messages: The message history before the final assistant message.
            assistant_message: The final assistant message containing the response content.
            raw: The raw response from the LLM.
            finish_reason: The reason why the LLM finished generating a response.
        """
        self.provider = provider
        self.model = model
        self.raw = raw
        self.finish_reason = finish_reason
        self.format_type = format

        self.messages = list(input_messages) + [assistant_message]

        found_format_tool = False
        self.texts, self.tool_calls, self.thinkings, self.content = [], [], [], []
        for part in assistant_message.content:
            if isinstance(part, ToolCall) and part.name == FORMAT_TOOL_NAME:
                part = Text(text=part.args)
                found_format_tool = True

            self.content.append(part)
            if isinstance(part, Text):
                self.texts.append(part)
            elif isinstance(part, ToolCall):
                self.tool_calls.append(part)
            elif isinstance(part, Thinking):
                self.thinkings.append(part)
            else:
                raise NotImplementedError

        if found_format_tool and self.finish_reason == FinishReason.TOOL_USE:
            self.finish_reason = FinishReason.END_TURN
