"""The `StreamChunk` class for handling streamed chunks from LLM calls."""

from dataclasses import dataclass

from typing_extensions import TypeVar

from ..tools import Tool
from ..types import Jsonable
from .base_stream_chunk import BaseStreamChunk
from .content import ResponseContent

T = TypeVar("T", bound=object | None, default=None)


@dataclass
class StreamChunk(BaseStreamChunk[ResponseContent, Tool[..., Jsonable], T]):
    """A chunk of a streaming response from an LLM.

    Stream chunks represent incremental pieces of a response that are delivered
    as they are generated by the model, allowing for real-time display and processing.
    """
