"""The `StreamChunk` class for handling streamed chunks from LLM calls."""

from dataclasses import dataclass
from decimal import Decimal
from typing import Any, Generic

from typing_extensions import TypeVar

from ..content import Audio, Image, Thinking, Video
from ..tools import ContextTool, Tool
from .content import ResponseContent
from .finish_reason import FinishReason
from .usage import Usage

T = TypeVar("T", bound=object | None, default=None)


@dataclass
class StreamChunk(Generic[T]):
    """A chunk of a streaming response from an LLM.

    Stream chunks represent incremental pieces of a response that are delivered
    as they are generated by the model, allowing for real-time display and processing.
    """

    content: ResponseContent
    """The content in this chunk of the response."""

    finish_reason: FinishReason | None
    """The reason why the LLM finished generating a response, if this is the final chunk."""

    usage: Usage | None
    """The token usage statistics for this chunk, if available."""

    cost: Decimal | None
    """The cost for this chunk, if available."""

    raw: Any
    """The raw chunk response from the LLM provider."""

    @property
    def text(self) -> str | None:
        """Returns the text content in this chunk, if any."""
        raise NotImplementedError()

    @property
    def image(self) -> Image | None:
        """Returns the image content in this chunk, if any."""
        raise NotImplementedError()

    @property
    def audio(self) -> Audio | None:
        """Returns the audio content in this chunk, if any."""
        raise NotImplementedError()

    @property
    def video(self) -> Video | None:
        """Returns the video content in this chunk, if any."""
        raise NotImplementedError()

    @property
    def thinking(self) -> Thinking | None:
        """Returns the thinking content in this chunk, if any."""
        raise NotImplementedError()

    @property
    def tool(self) -> Tool | ContextTool | None:
        """Returns the tool content in this chunk, if any."""
        raise NotImplementedError()

    def format(self) -> T:
        """Format the content of this chunk.

        Returns:
            The formatted content of this chunk.
        """
        raise NotImplementedError()

    def __repr__(self) -> str:
        """Return a string representation of the chunk content including embedded media.

        The resulting string includes all raw text directly, and includes placeholder
        representations for embedded media, eg {image: url=...} or {thinking: thoughts=...}

        Each content piece will be separated by newlines.
        """
        raise NotImplementedError()
