// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../index.js";

export interface OrganizationsCreatePaymentIntentResponse {
  clientSecret: string | null;
  amount: number;
  status: Mirascope.OrganizationsCreatePaymentIntentResponseStatus;
}
