// This file was auto-generated by Fern from our API Definition.

export const OrganizationsGetResponseRole = {
  Owner: "OWNER",
  Admin: "ADMIN",
  Member: "MEMBER",
  Bot: "BOT",
} as const;
export type OrganizationsGetResponseRole =
  (typeof OrganizationsGetResponseRole)[keyof typeof OrganizationsGetResponseRole];
