// This file was auto-generated by Fern from our API Definition.

export const OrganizationsSubscriptionResponseScheduledChangeTargetPlan = {
  Free: "free",
  Pro: "pro",
  Team: "team",
} as const;
export type OrganizationsSubscriptionResponseScheduledChangeTargetPlan =
  (typeof OrganizationsSubscriptionResponseScheduledChangeTargetPlan)[keyof typeof OrganizationsSubscriptionResponseScheduledChangeTargetPlan];
