// This file was auto-generated by Fern from our API Definition.

export const OrganizationsPreviewSubscriptionChangeResponseValidationErrorsItemResource =
  {
    Seats: "seats",
    Projects: "projects",
  } as const;
export type OrganizationsPreviewSubscriptionChangeResponseValidationErrorsItemResource =
  (typeof OrganizationsPreviewSubscriptionChangeResponseValidationErrorsItemResource)[keyof typeof OrganizationsPreviewSubscriptionChangeResponseValidationErrorsItemResource];
