# This file was auto-generated by Fern from our API Definition.

import typing

OrganizationsCreatePaymentIntentResponseStatus = typing.Union[
    typing.Literal["requires_payment", "requires_action", "succeeded"], typing.Any
]
