# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .organizations_list_response_organizations_item_role import (
    OrganizationsListResponseOrganizationsItemRole,
)


class OrganizationsListResponseOrganizationsItem(UniversalBaseModel):
    id: str
    name: str
    role: OrganizationsListResponseOrganizationsItemRole

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
