#!/usr/bin/env bun
/**
 * Local dev environment setup.
 *
 * Ensures everything is ready for `bun run dev`:
 * 1. Docker containers (Postgres + ClickHouse) are running
 * 2. .env.local exists with dev-safe defaults
 * 3. Drizzle migrations are applied
 * 4. Dev seed data exists (user, org, claw, session)
 *
 * Idempotent — safe to run repeatedly.
 *
 * Usage: bun run scripts/dev/setup.ts
 */
import { $ } from "bun";
import { existsSync, readFileSync } from "fs";
import path from "path";

const CLOUD_DIR = path.resolve(import.meta.dir, "../..");

// ---------------------------------------------------------------------------
// Known dev values (must match seed.ts)
// ---------------------------------------------------------------------------

const DB_URL =
  "postgres://postgres:postgres@localhost:5432/mirascope_cloud_dev";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function dockerIsRunning(): Promise<boolean> {
  try {
    await $`docker info`.quiet();
    return true;
  } catch {
    return false;
  }
}

async function containerIsRunning(name: string): Promise<boolean> {
  try {
    const result =
      await $`docker inspect -f '{{.State.Running}}' ${name}`.quiet();
    return result.text().trim() === "true";
  } catch {
    return false;
  }
}

async function waitForPostgres(maxAttempts = 30): Promise<void> {
  for (let i = 0; i < maxAttempts; i++) {
    try {
      await $`docker exec postgres-dev pg_isready -U postgres`.quiet();
      return;
    } catch {
      await new Promise((r) => setTimeout(r, 1000));
    }
  }
  throw new Error("Postgres did not become ready in time");
}

// ---------------------------------------------------------------------------
// Steps
// ---------------------------------------------------------------------------

async function ensureDocker() {
  if (!(await dockerIsRunning())) {
    console.error("❌ Docker is not running. Please start Docker Desktop.");
    process.exit(1);
  }
  console.log("🐳 Docker is running");
}

async function ensureContainers() {
  const pgRunning = await containerIsRunning("postgres-dev");
  const chRunning = await containerIsRunning("clickhouse-dev");

  if (pgRunning && chRunning) {
    console.log("🐘 Postgres + ClickHouse already running");
    return;
  }

  console.log("🐘 Starting Docker containers...");
  await $`docker compose -f ${CLOUD_DIR}/docker/compose.yml up -d`;
  console.log("⏳ Waiting for Postgres...");
  await waitForPostgres();
  console.log("🐘 Postgres ready");
}

function ensureEnvLocal() {
  const envPath = path.join(CLOUD_DIR, ".env.local");

  if (existsSync(envPath)) {
    // Check if it has DATABASE_URL
    const content = readFileSync(envPath, "utf-8");
    if (content.includes("DATABASE_URL")) {
      console.log("📄 .env.local exists");
      return;
    }
  }

  console.log("📄 Creating .env.local with dev defaults...");

  // Generate a random encryption key for claw secrets
  const encryptionKey = Buffer.from(
    crypto.getRandomValues(new Uint8Array(32)),
  ).toString("base64");

  const envContent = `# Auto-generated by scripts/dev/setup.ts
# Local development environment — all values are dev-safe defaults.

ENVIRONMENT=development
DATABASE_URL=${DB_URL}
SITE_URL=http://localhost:5173

# Auth (GitHub OAuth — register a dev app at https://github.com/settings/developers)
# Point callback to http://localhost:5173/auth/github/callback
GITHUB_CLIENT_ID=dev-github-client-id
GITHUB_CLIENT_SECRET=dev-github-client-secret
GITHUB_CALLBACK_URL=http://localhost:5173/auth/github/callback

# Google OAuth — register at https://console.cloud.google.com/apis/credentials
GOOGLE_CLIENT_ID=dev-google-client-id
GOOGLE_CLIENT_SECRET=dev-google-client-secret
GOOGLE_CALLBACK_URL=http://localhost:5173/auth/google/callback

# Stripe (use test mode keys from https://dashboard.stripe.com/test/apikeys)
STRIPE_SECRET_KEY=sk_test_dev_placeholder
STRIPE_WEBHOOK_SECRET=whsec_dev_placeholder
STRIPE_ROUTER_PRICE_ID=price_dev_router
STRIPE_ROUTER_METER_ID=meter_dev_router
STRIPE_CLOUD_FREE_PRICE_ID=price_dev_free
STRIPE_CLOUD_PRO_PRICE_ID=price_dev_pro
STRIPE_CLOUD_TEAM_PRICE_ID=price_dev_team
STRIPE_CLOUD_SPANS_PRICE_ID=price_dev_spans
STRIPE_CLOUD_SPANS_METER_ID=meter_dev_spans

# Resend (email)
RESEND_API_KEY=re_dev_placeholder
RESEND_AUDIENCE_SEGMENT_ID=dev-audience-segment

# Router provider keys (not needed for local claw dev)
OPENAI_API_KEY=sk-dev-placeholder
ANTHROPIC_API_KEY=sk-ant-dev-placeholder
GEMINI_API_KEY=dev-gemini-placeholder

# ClickHouse
CLICKHOUSE_URL=http://localhost:8123
CLICKHOUSE_USER=default
CLICKHOUSE_PASSWORD=clickhouse
CLICKHOUSE_DATABASE=mirascope_analytics
CLICKHOUSE_TLS_ENABLED=false
CLICKHOUSE_TLS_CA=
CLICKHOUSE_TLS_SKIP_VERIFY=false
CLICKHOUSE_TLS_HOSTNAME_VERIFY=true
CLICKHOUSE_TLS_MIN_VERSION=1.2

# Analytics (PostHog + GA — not needed locally)
POSTHOG_API_KEY=phc_dev_placeholder
POSTHOG_HOST=https://us.i.posthog.com
GOOGLE_ANALYTICS_MEASUREMENT_ID=G-DEV000000
GOOGLE_ANALYTICS_API_SECRET=dev-ga-secret

# Frontend (Vite)
VITE_STRIPE_PUBLISHABLE_KEY=pk_test_dev_placeholder
VITE_POSTHOG_API_KEY=phc_dev_placeholder
VITE_POSTHOG_HOST=https://us.i.posthog.com
VITE_GOOGLE_ANALYTICS_MEASUREMENT_ID=G-DEV000000

# Cloudflare (not needed for local dev, but required by settings validation)
CLOUDFLARE_ACCOUNT_ID=dev-cf-account
CLOUDFLARE_API_TOKEN=dev-cf-token
CF_R2_READ_PERMISSION_GROUP_ID=dev-r2-read
CF_R2_WRITE_PERMISSION_GROUP_ID=dev-r2-write
CF_DO_NAMESPACE_ID=dev-do-namespace
CF_DISPATCH_WORKER_BASE_URL=http://localhost:8787

# Encryption key for claw secrets
CLAW_SECRETS_ENCRYPTION_KEY_V1=${encryptionKey}

# OpenClaw gateway (for local WS proxy — connects chat UI to your local gateway)
# Uncomment and set these to enable chat via the Vite dev server:
# OPENCLAW_GATEWAY_WS_URL=ws://localhost:18789
# OPENCLAW_GATEWAY_TOKEN=your-gateway-token-here
# Vite-exposed version (used by chat.tsx for the "Open Gateway" link)
# VITE_OPENCLAW_GATEWAY_WS_URL=ws://localhost:18789
`;

  Bun.write(envPath, envContent);
  console.log("📄 Created .env.local");
  console.log(
    "   ⚠️  Edit OPENCLAW_GATEWAY_WS_URL and OPENCLAW_GATEWAY_TOKEN to enable chat",
  );
}

async function runMigrations() {
  console.log("🔄 Running Drizzle migrations...");
  await $`cd ${CLOUD_DIR} && bunx drizzle-kit migrate`.env({
    ...process.env,
    DATABASE_URL: DB_URL,
  });
  console.log("✅ Migrations complete");
}

async function runSeed() {
  console.log("🌱 Running seed...");
  await $`cd ${CLOUD_DIR} && bun run scripts/dev/seed.ts`.env({
    ...process.env,
    DATABASE_URL: DB_URL,
  });
}

async function printReadyMessage() {
  console.log("\n" + "=".repeat(60));
  console.log("🚀 Dev environment ready!");
  console.log("=".repeat(60));
  console.log("");
  console.log("Auth is automatic — no login needed.");
  console.log("Once Vite starts, navigate to: /test-org/claws/test-claw/chat");
  console.log("");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log("🔧 Setting up local dev environment...\n");

  await ensureDocker();
  await ensureContainers();
  ensureEnvLocal();
  await runMigrations();
  await runSeed();
  await printReadyMessage();
}

main().catch((err) => {
  console.error("❌ Setup failed:", err);
  process.exit(1);
});
