"""The `llm.messages.content` module."""

from typing import TypeAlias

from .audio import Audio, Base64AudioSource
from .document import Document
from .image import Base64ImageSource, Image, URLImageSource
from .text import Text, TextChunk, TextEndChunk, TextStartChunk
from .thinking import Thinking, ThinkingChunk, ThinkingEndChunk, ThinkingStartChunk
from .tool_call import ToolCall, ToolCallChunk, ToolCallEndChunk, ToolCallStartChunk
from .tool_output import ToolOutput

ContentPart: TypeAlias = (
    Text | Image | Audio | Document | ToolOutput | ToolCall | Thinking
)
"""Content parts that may be included in a Message."""

UserContentPart: TypeAlias = Text | Image | Audio | Document | ToolOutput
"""Content parts that can be included in a UserMessage."""

AssistantContentPart: TypeAlias = Text | ToolCall | Thinking
"""Content parts that can be included in an AssistantMessage."""

AssistantContentChunk: TypeAlias = (
    TextStartChunk
    | TextChunk
    | TextEndChunk
    | ThinkingStartChunk
    | ThinkingChunk
    | ThinkingEndChunk
    | ToolCallStartChunk
    | ToolCallChunk
    | ToolCallEndChunk
)
"""Chunks of assistant content that may be streamed as generated by the LLM."""

__all__ = [
    "AssistantContentChunk",
    "AssistantContentPart",
    "Audio",
    "Base64AudioSource",
    "Base64ImageSource",
    "ContentPart",
    "Document",
    "Image",
    "Text",
    "TextChunk",
    "TextEndChunk",
    "TextStartChunk",
    "Thinking",
    "ThinkingChunk",
    "ThinkingEndChunk",
    "ThinkingStartChunk",
    "ToolCall",
    "ToolCallChunk",
    "ToolCallEndChunk",
    "ToolCallStartChunk",
    "ToolOutput",
    "URLImageSource",
    "UserContentPart",
]
