"""The `llm.messages.content` module."""

from typing import TypeAlias

from .audio import Audio, AudioUrl
from .document import Document
from .image import Image, ImageUrl
from .text import Text, TextChunk, TextEndChunk, TextStartChunk
from .thinking import Thinking, ThinkingChunk, ThinkingEndChunk, ThinkingStartChunk
from .tool_call import ToolCall, ToolCallChunk, ToolCallEndChunk, ToolCallStartChunk
from .tool_output import ToolOutput

ContentPart: TypeAlias = (
    Text
    | Image
    | ImageUrl
    | Audio
    | AudioUrl
    | Document
    | ToolOutput
    | ToolCall
    | Thinking
)
"""Content parts that may be included in a Message."""

UserContentPart: TypeAlias = (
    Text | Image | ImageUrl | Audio | AudioUrl | Document | ToolOutput
)
"""Content parts that can be included in a UserMessage."""

AssistantContentPart: TypeAlias = Text | ToolCall | Thinking
"""Content parts that can be included in an AssistantMessage."""

AssistantContentChunk: TypeAlias = (
    TextStartChunk
    | TextChunk
    | TextEndChunk
    | ThinkingStartChunk
    | ThinkingChunk
    | ThinkingEndChunk
    | ToolCallStartChunk
    | ToolCallChunk
    | ToolCallEndChunk
)
"""Chunks of assistant content that may be streamed as generated by the LLM."""

__all__ = [
    "AssistantContentChunk",
    "AssistantContentPart",
    "Audio",
    "AudioUrl",
    "ContentPart",
    "Document",
    "Image",
    "ImageUrl",
    "Text",
    "TextChunk",
    "TextEndChunk",
    "TextStartChunk",
    "Thinking",
    "ThinkingChunk",
    "ThinkingEndChunk",
    "ThinkingStartChunk",
    "ToolCall",
    "ToolCallChunk",
    "ToolCallEndChunk",
    "ToolCallStartChunk",
    "ToolOutput",
    "UserContentPart",
]
