"""The `llm.messages.content` module."""

from typing import TypeAlias

from .audio import Audio, Base64AudioSource
from .document import (
    Base64DocumentSource,
    Document,
    TextDocumentSource,
    URLDocumentSource,
)
from .image import Base64ImageSource, Image, URLImageSource
from .text import Text, TextChunk, TextEndChunk, TextStartChunk
from .thinking_signature import (
    ThinkingSignature,
    ThinkingSignatureChunk,
    ThinkingSignatureEndChunk,
    ThinkingSignatureStartChunk,
)
from .thought import Thought, ThoughtChunk, ThoughtEndChunk, ThoughtStartChunk
from .tool_call import ToolCall, ToolCallChunk, ToolCallEndChunk, ToolCallStartChunk
from .tool_output import ToolOutput

ContentPart: TypeAlias = (
    Text
    | Image
    | Audio
    | Document
    | ToolOutput
    | ToolCall
    | Thought
    | ThinkingSignature
)
"""Content parts that may be included in a Message."""

UserContentPart: TypeAlias = Text | Image | Audio | Document | ToolOutput
"""Content parts that can be included in a UserMessage."""

AssistantContentPart: TypeAlias = Text | ToolCall | Thought | ThinkingSignature
"""Content parts that can be included in an AssistantMessage."""

AssistantContentChunk: TypeAlias = (
    TextStartChunk
    | TextChunk
    | TextEndChunk
    | ThoughtStartChunk
    | ThoughtChunk
    | ThoughtEndChunk
    | ToolCallStartChunk
    | ToolCallChunk
    | ToolCallEndChunk
    | ThinkingSignatureStartChunk
    | ThinkingSignatureChunk
    | ThinkingSignatureEndChunk
)
"""Chunks of assistant content that may be streamed as generated by the LLM."""

__all__ = [
    "AssistantContentChunk",
    "AssistantContentPart",
    "Audio",
    "Base64AudioSource",
    "Base64DocumentSource",
    "Base64ImageSource",
    "ContentPart",
    "Document",
    "Image",
    "Text",
    "TextChunk",
    "TextDocumentSource",
    "TextEndChunk",
    "TextStartChunk",
    "ThinkingSignature",
    "ThinkingSignatureChunk",
    "ThinkingSignatureEndChunk",
    "ThinkingSignatureStartChunk",
    "Thought",
    "ThoughtChunk",
    "ThoughtEndChunk",
    "ThoughtStartChunk",
    "ToolCall",
    "ToolCallChunk",
    "ToolCallEndChunk",
    "ToolCallStartChunk",
    "ToolOutput",
    "URLDocumentSource",
    "URLImageSource",
    "UserContentPart",
]
