// This file was auto-generated by Fern from our API Definition.

export interface TokenCostCalculateResponse {
  inputCostCenticents: number;
  outputCostCenticents: number;
  cacheReadCostCenticents?: number;
  cacheWriteCostCenticents?: number;
  totalCostCenticents: number;
  inputCostDollars: number;
  outputCostDollars: number;
  cacheReadCostDollars?: number;
  cacheWriteCostDollars?: number;
  totalCostDollars: number;
}
