// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";

export const OrganizationsSubscriptionResponseCurrentPlan: core.serialization.Schema<
  serializers.OrganizationsSubscriptionResponseCurrentPlan.Raw,
  Mirascope.OrganizationsSubscriptionResponseCurrentPlan
> = core.serialization.enum_(["free", "pro", "team"]);

export declare namespace OrganizationsSubscriptionResponseCurrentPlan {
  export type Raw = "free" | "pro" | "team";
}
