// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";
import { OrganizationsUpdateResponseRole } from "./OrganizationsUpdateResponseRole.js";

export const OrganizationsUpdateResponse: core.serialization.ObjectSchema<
  serializers.OrganizationsUpdateResponse.Raw,
  Mirascope.OrganizationsUpdateResponse
> = core.serialization.object({
  id: core.serialization.string(),
  name: core.serialization.string(),
  slug: core.serialization.string(),
  stripeCustomerId: core.serialization.string(),
  role: OrganizationsUpdateResponseRole,
});

export declare namespace OrganizationsUpdateResponse {
  export interface Raw {
    id: string;
    name: string;
    slug: string;
    stripeCustomerId: string;
    role: OrganizationsUpdateResponseRole.Raw;
  }
}
