// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";
import { Date_ } from "../../../types/Date_.js";
import { ClawMembershipsGetResponseRole } from "./ClawMembershipsGetResponseRole.js";

export const ClawMembershipsGetResponse: core.serialization.ObjectSchema<
  serializers.ClawMembershipsGetResponse.Raw,
  Mirascope.ClawMembershipsGetResponse
> = core.serialization.object({
  memberId: core.serialization.string(),
  organizationId: core.serialization.string(),
  clawId: core.serialization.string(),
  role: ClawMembershipsGetResponseRole,
  createdAt: Date_.nullable(),
});

export declare namespace ClawMembershipsGetResponse {
  export interface Raw {
    memberId: string;
    organizationId: string;
    clawId: string;
    role: ClawMembershipsGetResponseRole.Raw;
    createdAt?: Date_.Raw | null;
  }
}
