// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";
import { Date_ } from "../../../types/Date_.js";
import { OrganizationMembershipsListResponseItemRole } from "./OrganizationMembershipsListResponseItemRole.js";

export const OrganizationMembershipsListResponseItem: core.serialization.ObjectSchema<
  serializers.OrganizationMembershipsListResponseItem.Raw,
  Mirascope.OrganizationMembershipsListResponseItem
> = core.serialization.object({
  memberId: core.serialization.string(),
  email: core.serialization.string(),
  name: core.serialization.string().nullable(),
  role: OrganizationMembershipsListResponseItemRole,
  createdAt: Date_.nullable(),
});

export declare namespace OrganizationMembershipsListResponseItem {
  export interface Raw {
    memberId: string;
    email: string;
    name?: string | null;
    role: OrganizationMembershipsListResponseItemRole.Raw;
    createdAt?: Date_.Raw | null;
  }
}
