// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";

export const AnnotationsGetResponseLabel: core.serialization.Schema<
  serializers.AnnotationsGetResponseLabel.Raw,
  Mirascope.AnnotationsGetResponseLabel
> = core.serialization.enum_(["pass", "fail"]);

export declare namespace AnnotationsGetResponseLabel {
  export type Raw = "pass" | "fail";
}
