// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";
import { AnnotationsListResponseAnnotationsItem } from "./AnnotationsListResponseAnnotationsItem.js";

export const AnnotationsListResponse: core.serialization.ObjectSchema<
  serializers.AnnotationsListResponse.Raw,
  Mirascope.AnnotationsListResponse
> = core.serialization.object({
  annotations: core.serialization.list(AnnotationsListResponseAnnotationsItem),
  total: core.serialization.number(),
});

export declare namespace AnnotationsListResponse {
  export interface Raw {
    annotations: AnnotationsListResponseAnnotationsItem.Raw[];
    total: number;
  }
}
