// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";

export const AnnotationsCreateRequestLabel: core.serialization.Schema<
  serializers.AnnotationsCreateRequestLabel.Raw,
  Mirascope.AnnotationsCreateRequestLabel
> = core.serialization.enum_(["pass", "fail"]);

export declare namespace AnnotationsCreateRequestLabel {
  export type Raw = "pass" | "fail";
}
