// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../index.js";

/**
 * an object to be decoded into a globally shared symbol
 */
export interface PropertyKeyKey {
  tag: Mirascope.PropertyKeyKeyTag;
  key: string;
}
