// This file was auto-generated by Fern from our API Definition.

export const StripeErrorTag = {
  StripeError: "StripeError",
} as const;
export type StripeErrorTag =
  (typeof StripeErrorTag)[keyof typeof StripeErrorTag];
