// This file was auto-generated by Fern from our API Definition.

export const SubscriptionPastDueErrorTag = {
  SubscriptionPastDueError: "SubscriptionPastDueError",
} as const;
export type SubscriptionPastDueErrorTag =
  (typeof SubscriptionPastDueErrorTag)[keyof typeof SubscriptionPastDueErrorTag];
