/**
 * Code generation for Google model info from test results.
 *
 * Reads python/scripts/model_features/data/google.yaml and generates
 * typescript/mirascope/src/llm/providers/google/model-info.ts
 *
 * See index.ts for explanation of why codegen exists in both Python and TypeScript.
 */

import { parse as parseYaml } from 'yaml';
import * as fs from 'node:fs';
import * as path from 'node:path';

interface FeatureResult {
  status?: string;
}

interface ModelInfo {
  features?: {
    chat_model?: FeatureResult;
    structured_output_with_tools?: FeatureResult;
  };
}

interface YamlData {
  models?: Record<string, ModelInfo>;
}

/**
 * Collect model IDs and models without structured output + tools support.
 */
function collectModelData(data: YamlData): {
  modelIds: string[];
  modelsWithoutSupport: string[];
} {
  const modelIds: string[] = [];
  const modelsWithoutSupport = new Set<string>();

  const modelsData = data.models ?? {};

  for (const [modelId, modelInfo] of Object.entries(modelsData).sort()) {
    const features = modelInfo.features ?? {};

    // Check if model supports chat
    const chatResult = features.chat_model ?? {};
    const chatSupported = chatResult.status === 'supported';

    // Skip models that don't support chat
    if (!chatSupported) {
      continue;
    }

    // Add model ID
    modelIds.push(`google/${modelId}`);

    // Check structured output with tools support
    const structuredOutputToolsResult =
      features.structured_output_with_tools ?? {};
    const supportsStructuredOutputAndTools =
      structuredOutputToolsResult.status === 'supported';

    if (!supportsStructuredOutputAndTools) {
      modelsWithoutSupport.add(modelId);
    }
  }

  return {
    modelIds,
    modelsWithoutSupport: [...modelsWithoutSupport].sort(),
  };
}

/**
 * Generate the TypeScript model-info.ts file content.
 */
function generateModelInfoContent(
  modelIds: string[],
  modelsWithoutSupport: string[]
): string {
  const lines: string[] = [
    '/**',
    ' * Google model information.',
    ' *',
    ' * This file is auto-generated by typescript/scripts/codegen/google.ts',
    ' * Do not edit manually - run `bun run codegen` to update.',
    ' */',
    '',
    '/**',
    ' * Valid Google model IDs.',
    ' */',
    'export type GoogleKnownModels =',
  ];

  // Add model IDs as union type
  for (let i = 0; i < modelIds.length; i++) {
    const semicolon = i === modelIds.length - 1 ? ';' : '';
    lines.push(`  | '${modelIds[i]}'${semicolon}`);
  }

  lines.push('');
  lines.push('/**');
  lines.push(
    ' * Models that do not support structured outputs when tools are present.'
  );
  lines.push(' */');
  lines.push(
    'export const MODELS_WITHOUT_STRUCTURED_OUTPUT_AND_TOOLS_SUPPORT: ReadonlySet<string> ='
  );
  lines.push('  new Set([');

  for (const modelId of modelsWithoutSupport) {
    lines.push(`    '${modelId}',`);
  }

  lines.push('  ]);');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate Google model info from YAML test data.
 */
export function generateGoogleModelInfo(): void {
  const scriptDir = import.meta.dirname;
  const repoRoot = path.resolve(scriptDir, '../../..');
  const inputPath = path.join(
    repoRoot,
    'python/scripts/model_features/data/google.yaml'
  );
  const outputPath = path.join(
    repoRoot,
    'typescript/mirascope/src/llm/providers/google/model-info.ts'
  );

  // Check input exists
  if (!fs.existsSync(inputPath)) {
    console.error(`Error: Input file not found: ${inputPath}`);
    console.error(
      'Run Python test script first: cd python && uv run python -m scripts.model_features.test_google'
    );
    process.exit(1);
  }

  // Load YAML
  console.log(`Reading test results from: ${inputPath}`);
  const yamlContent = fs.readFileSync(inputPath, 'utf-8');
  const data = parseYaml(yamlContent) as YamlData;

  // Collect model data
  console.log('Collecting model data...');
  const { modelIds, modelsWithoutSupport } = collectModelData(data);

  // Generate TypeScript code
  console.log('Generating TypeScript model info...');
  const content = generateModelInfoContent(modelIds, modelsWithoutSupport);

  // Write file
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content);
  console.log(`  Generated: ${outputPath}`);

  // Show stats
  const modelsData = data.models ?? {};
  const discoveredModelCount = Object.keys(modelsData).length;
  const chatModelCount = Object.values(modelsData).filter(
    (info) => info.features?.chat_model?.status === 'supported'
  ).length;

  console.log(`  Discovered models: ${discoveredModelCount}`);
  console.log(`  Chat models (generated): ${chatModelCount}`);
  console.log(
    `  Models without structured output + tools support: ${modelsWithoutSupport.length}`
  );
}

// Run if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  generateGoogleModelInfo();
}
