// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../../api/index.js";
import type * as serializers from "../../../../index.js";

import * as core from "../../../../../core/index.js";
import { ClawMembershipsCreateRequestRole } from "../../types/ClawMembershipsCreateRequestRole.js";

export const ClawMembershipsCreateRequest: core.serialization.Schema<
  serializers.ClawMembershipsCreateRequest.Raw,
  Omit<Mirascope.ClawMembershipsCreateRequest, "organizationId" | "clawId">
> = core.serialization.object({
  memberId: core.serialization.string(),
  role: ClawMembershipsCreateRequestRole,
});

export declare namespace ClawMembershipsCreateRequest {
  export interface Raw {
    memberId: string;
    role: ClawMembershipsCreateRequestRole.Raw;
  }
}
