"""The `StructuredAgent` module for creating agents with structured responses."""

from collections.abc import Sequence
from dataclasses import dataclass

from typing_extensions import TypeVar

from ..content import Content
from ..responses import (
    AsyncStructuredStream,
    Response,
    StructuredStream,
)
from ..types import Dataclass
from .base_structured_agent import (
    BaseStructuredAgent,
)

DepsT = TypeVar("DepsT", default=None)
T = TypeVar("T", bound=Dataclass | None, default=None)


@dataclass
class StructuredAgent(BaseStructuredAgent[DepsT, T]):
    """Structured agent class for generating structured responses using LLMs with tools."""

    def __call__(
        self, query: Content | Sequence[Content], *, deps: DepsT = None
    ) -> Response[T]:
        """Generates a structured response by running the agent loop."""
        raise NotImplementedError()

    async def run_async(
        self, query: Content | Sequence[Content], *, deps: DepsT = None
    ) -> Response[T]:
        """Generates a structured response by running the agent loop asynchronously."""
        raise NotImplementedError()

    def stream(
        self, query: Content | Sequence[Content], *, deps: DepsT = None
    ) -> StructuredStream[T]:
        """Streams the structured response generated by running the agent loop."""
        raise NotImplementedError()

    async def stream_async(
        self, query: Content | Sequence[Content], *, deps: DepsT = None
    ) -> AsyncStructuredStream[T]:
        """Streams the structured response generated by running the agent loop asynchronously."""
        raise NotImplementedError()
