# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .http_api_decode_error_tag import HttpApiDecodeErrorTag
from .issue import Issue


class HttpApiDecodeError(UniversalBaseModel):
    """
    The request did not match the expected schema
    """

    issues: typing.List[Issue]
    message: str
    tag: typing_extensions.Annotated[HttpApiDecodeErrorTag, FieldMetadata(alias="_tag")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
