# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .resource import Resource
from .scope_spans import ScopeSpans


class ResourceSpans(UniversalBaseModel):
    resource: typing.Optional[Resource] = None
    scope_spans: typing_extensions.Annotated[
        typing.List[ScopeSpans], FieldMetadata(alias="scopeSpans")
    ]
    schema_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="schemaUrl")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
