// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";

export const ApiKeysListAllForOrgResponseItem: core.serialization.ObjectSchema<
  serializers.ApiKeysListAllForOrgResponseItem.Raw,
  Mirascope.ApiKeysListAllForOrgResponseItem
> = core.serialization.object({
  id: core.serialization.string(),
  name: core.serialization.string(),
  keyPrefix: core.serialization.string(),
  environmentId: core.serialization.string(),
  ownerId: core.serialization.string(),
  createdAt: core.serialization.string().nullable(),
  lastUsedAt: core.serialization.string().nullable(),
  projectId: core.serialization.string(),
  projectName: core.serialization.string(),
  environmentName: core.serialization.string(),
});

export declare namespace ApiKeysListAllForOrgResponseItem {
  export interface Raw {
    id: string;
    name: string;
    keyPrefix: string;
    environmentId: string;
    ownerId: string;
    createdAt?: string | null;
    lastUsedAt?: string | null;
    projectId: string;
    projectName: string;
    environmentName: string;
  }
}
