// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";

export const ClawsGetResponseInstanceType: core.serialization.Schema<
  serializers.ClawsGetResponseInstanceType.Raw,
  Mirascope.ClawsGetResponseInstanceType
> = core.serialization.enum_([
  "lite",
  "basic",
  "standard-1",
  "standard-2",
  "standard-3",
  "standard-4",
]);

export declare namespace ClawsGetResponseInstanceType {
  export type Raw =
    | "lite"
    | "basic"
    | "standard-1"
    | "standard-2"
    | "standard-3"
    | "standard-4";
}
