// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";
import { BigInt } from "../../../types/BigInt.js";
import { Date_ } from "../../../types/Date_.js";

export const ClawsGetUsageResponse: core.serialization.ObjectSchema<
  serializers.ClawsGetUsageResponse.Raw,
  Mirascope.ClawsGetUsageResponse
> = core.serialization.object({
  weeklyUsageCenticents: BigInt,
  weeklyWindowStart: Date_.nullable(),
  burstUsageCenticents: BigInt,
  burstWindowStart: Date_.nullable(),
  weeklySpendingGuardrailCenticents: BigInt.nullable(),
  poolUsageCenticents: BigInt,
  poolLimitCenticents: core.serialization.number(),
  poolPercentUsed: core.serialization.number(),
});

export declare namespace ClawsGetUsageResponse {
  export interface Raw {
    weeklyUsageCenticents: BigInt.Raw;
    weeklyWindowStart?: Date_.Raw | null;
    burstUsageCenticents: BigInt.Raw;
    burstWindowStart?: Date_.Raw | null;
    weeklySpendingGuardrailCenticents?: BigInt.Raw | null;
    poolUsageCenticents: BigInt.Raw;
    poolLimitCenticents: number;
    poolPercentUsed: number;
  }
}
