// This file was auto-generated by Fern from our API Definition.

export const ProjectMembershipsUpdateResponseRole = {
  Admin: "ADMIN",
  Developer: "DEVELOPER",
  Viewer: "VIEWER",
  Annotator: "ANNOTATOR",
} as const;
export type ProjectMembershipsUpdateResponseRole =
  (typeof ProjectMembershipsUpdateResponseRole)[keyof typeof ProjectMembershipsUpdateResponseRole];
