// This file was auto-generated by Fern from our API Definition.

export const ProjectMembershipsCreateResponseRole = {
  Admin: "ADMIN",
  Developer: "DEVELOPER",
  Viewer: "VIEWER",
  Annotator: "ANNOTATOR",
} as const;
export type ProjectMembershipsCreateResponseRole =
  (typeof ProjectMembershipsCreateResponseRole)[keyof typeof ProjectMembershipsCreateResponseRole];
