"""The `llm` module for writing provider-agnostic LLM Generations.

This module provides a unified interface for interacting with different LLM providers,
including messages, tools, response formatting, and streaming. It allows you to write
code that works with multiple LLM providers without changing your application logic.
"""

# TODO: Across the API, audit docstrings to ensure they are compliant Google-style docstrings
# (Write some tooling to ensure this happens consistently + in CI)

from . import (
    calls,
    clients,
    content,
    exceptions,
    formatting,
    mcp,
    messages,
    models,
    prompts,
    responses,
    streams,
    tools,
    types,
)
from .calls import call
from .clients import ModelId, Provider, client, get_client
from .content import (
    AssistantContentChunk,
    AssistantContentPart,
    Audio,
    Document,
    Image,
    ImageUrl,
    Text,
    TextChunk,
    TextEndChunk,
    TextStartChunk,
    Thinking,
    ThinkingChunk,
    ThinkingEndChunk,
    ThinkingStartChunk,
    ToolCall,
    ToolCallChunk,
    ToolCallEndChunk,
    ToolCallStartChunk,
    ToolOutput,
    UserContentPart,
)
from .context import Context
from .exceptions import (
    APIError,
    AuthenticationError,
    BadRequestError,
    ConnectionError,
    FeatureNotSupportedError,
    FormattingModeNotSupportedError,
    MirascopeError,
    NotFoundError,
    PermissionError,
    RateLimitError,
    ServerError,
    TimeoutError,
    ToolNotFoundError,
)
from .formatting import Format, FormattingMode, Partial, format
from .messages import AssistantMessage, Message, SystemMessage, UserMessage
from .models import Model, model
from .prompts import prompt
from .responses import (
    AsyncChunkIterator,
    AsyncContextResponse,
    AsyncContextStreamResponse,
    AsyncResponse,
    AsyncStreamResponse,
    ChunkIterator,
    ContextResponse,
    ContextStreamResponse,
    FinishReason,
    Response,
    StreamResponse,
)
from .streams import AsyncStream, Stream
from .tools import (
    AsyncContextTool,
    AsyncContextToolkit,
    AsyncTool,
    AsyncToolkit,
    ContextTool,
    ContextToolkit,
    Tool,
    Toolkit,
    tool,
)

__all__ = [
    "APIError",
    "AssistantContentChunk",
    "AssistantContentPart",
    "AssistantMessage",
    "AsyncChunkIterator",
    "AsyncContextResponse",
    "AsyncContextStreamResponse",
    "AsyncContextTool",
    "AsyncContextToolkit",
    "AsyncResponse",
    "AsyncStream",
    "AsyncStreamResponse",
    "AsyncTool",
    "AsyncToolkit",
    "Audio",
    "AuthenticationError",
    "BadRequestError",
    "ChunkIterator",
    "ConnectionError",
    "Context",
    "ContextResponse",
    "ContextStreamResponse",
    "ContextTool",
    "ContextToolkit",
    "Document",
    "FeatureNotSupportedError",
    "FinishReason",
    "Format",
    "FormattingMode",
    "FormattingModeNotSupportedError",
    "Image",
    "ImageUrl",
    "Message",
    "MirascopeError",
    "Model",
    "NotFoundError",
    "Partial",
    "PermissionError",
    "RateLimitError",
    "Response",
    "ServerError",
    "Stream",
    "StreamResponse",
    "StreamResponse",
    "SystemMessage",
    "Text",
    "TextChunk",
    "TextEndChunk",
    "TextStartChunk",
    "Thinking",
    "ThinkingChunk",
    "ThinkingEndChunk",
    "ThinkingStartChunk",
    "TimeoutError",
    "Tool",
    "ToolCall",
    "ToolCallChunk",
    "ToolCallEndChunk",
    "ToolCallStartChunk",
    "ToolNotFoundError",
    "ToolOutput",
    "Toolkit",
    "UserContentPart",
    "UserMessage",
    "call",
    "calls",
    "client",
    "clients",
    "content",
    "exceptions",
    "format",
    "formatting",
    "get_client",
    "mcp",
    "messages",
    "model",
    "models",
    "prompt",
    "prompts",
    "responses",
    "streams",
    "tool",
    "tools",
    "types",
]
