"""The `llm` module for writing provider-agnostic LLM Generations.

This module provides a unified interface for interacting with different LLM providers,
including messages, tools, response formatting, and streaming. It allows you to write
code that works with multiple LLM providers without changing your application logic.
"""

from . import (
    agents,
    calls,
    clients,
    content,
    exceptions,
    formatting,
    mcp,
    messages,
    models,
    prompts,
    responses,
    streams,
    tools,
    types,
)
from .agents import Agent, AgentTemplate, AsyncAgent, AsyncAgentTemplate, agent
from .calls import call, context_call
from .clients import AnthropicClient, GoogleClient, OpenAIClient
from .content import (
    AssistantContentChunk,
    AssistantContentPart,
    Audio,
    Document,
    FinishReasonChunk,
    Image,
    ImageUrl,
    Text,
    TextChunk,
    TextEndChunk,
    TextStartChunk,
    Thinking,
    ThinkingChunk,
    ThinkingEndChunk,
    ThinkingStartChunk,
    ToolCall,
    ToolCallChunk,
    ToolCallEndChunk,
    ToolCallStartChunk,
    ToolOutput,
    UserContentPart,
)
from .context import Context
from .exceptions import (
    APIError,
    AuthenticationError,
    BadRequestError,
    ConnectionError,
    MirascopeError,
    NotFoundError,
    PermissionError,
    RateLimitError,
    ServerError,
    TimeoutError,
    ToolNotFoundError,
)
from .formatting import Format, Partial, format
from .messages import AssistantMessage, Message, SystemMessage, UserMessage
from .models import LLM, model
from .prompts import prompt
from .responses import (
    AsyncChunkIterator,
    AsyncStreamResponse,
    ChunkIterator,
    FinishReason,
    Response,
    StreamResponse,
)
from .streams import AsyncStream, Stream
from .tools import (
    AsyncContextTool,
    AsyncContextToolkit,
    AsyncTool,
    AsyncToolkit,
    ContextTool,
    ContextToolkit,
    Tool,
    Toolkit,
    context_tool,
    tool,
)

__all__ = [
    "LLM",
    "APIError",
    "Agent",
    "AgentTemplate",
    "AnthropicClient",
    "AssistantContentChunk",
    "AssistantContentPart",
    "AssistantMessage",
    "AsyncAgent",
    "AsyncAgentTemplate",
    "AsyncChunkIterator",
    "AsyncContextTool",
    "AsyncContextToolkit",
    "AsyncStream",
    "AsyncStreamResponse",
    "AsyncTool",
    "AsyncToolkit",
    "Audio",
    "AuthenticationError",
    "BadRequestError",
    "ChunkIterator",
    "ConnectionError",
    "Context",
    "ContextTool",
    "ContextToolkit",
    "Document",
    "FinishReason",
    "FinishReasonChunk",
    "Format",
    "GoogleClient",
    "Image",
    "ImageUrl",
    "Message",
    "MirascopeError",
    "NotFoundError",
    "OpenAIClient",
    "Partial",
    "PermissionError",
    "RateLimitError",
    "Response",
    "ServerError",
    "Stream",
    "StreamResponse",
    "StreamResponse",
    "SystemMessage",
    "Text",
    "TextChunk",
    "TextEndChunk",
    "TextStartChunk",
    "Thinking",
    "ThinkingChunk",
    "ThinkingEndChunk",
    "ThinkingStartChunk",
    "TimeoutError",
    "Tool",
    "Tool",
    "ToolCall",
    "ToolCallChunk",
    "ToolCallEndChunk",
    "ToolCallStartChunk",
    "ToolNotFoundError",
    "ToolOutput",
    "Toolkit",
    "UserContentPart",
    "UserMessage",
    "agent",
    "agents",
    "call",
    "calls",
    "clients",
    "content",
    "context_call",
    "context_tool",
    "exceptions",
    "format",
    "formatting",
    "mcp",
    "messages",
    "model",
    "models",
    "prompts",
    "responses",
    "streams",
    "tool",
    "tools",
    "types",
]
