// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";
import { TracesCreateRequestResourceSpansItemScopeSpansItemSpansItemAttributesItemValue } from "./TracesCreateRequestResourceSpansItemScopeSpansItemSpansItemAttributesItemValue.js";

export const TracesCreateRequestResourceSpansItemScopeSpansItemSpansItemAttributesItem: core.serialization.ObjectSchema<
  serializers.TracesCreateRequestResourceSpansItemScopeSpansItemSpansItemAttributesItem.Raw,
  Mirascope.TracesCreateRequestResourceSpansItemScopeSpansItemSpansItemAttributesItem
> = core.serialization.object({
  key: core.serialization.string(),
  value:
    TracesCreateRequestResourceSpansItemScopeSpansItemSpansItemAttributesItemValue,
});

export declare namespace TracesCreateRequestResourceSpansItemScopeSpansItemSpansItemAttributesItem {
  export interface Raw {
    key: string;
    value: TracesCreateRequestResourceSpansItemScopeSpansItemSpansItemAttributesItemValue.Raw;
  }
}
