// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";

export const TracesCreateOtelRequestResourceSpansItemResourceAttributesItemValueIntValue: core.serialization.Schema<
  serializers.TracesCreateOtelRequestResourceSpansItemResourceAttributesItemValueIntValue.Raw,
  Mirascope.TracesCreateOtelRequestResourceSpansItemResourceAttributesItemValueIntValue
> = core.serialization.undiscriminatedUnion([
  core.serialization.string(),
  core.serialization.number(),
]);

export declare namespace TracesCreateOtelRequestResourceSpansItemResourceAttributesItemValueIntValue {
  export type Raw = string | number;
}
