// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";

export const TracesGetAnalyticsSummaryResponseTopFunctionsItem: core.serialization.ObjectSchema<
  serializers.TracesGetAnalyticsSummaryResponseTopFunctionsItem.Raw,
  Mirascope.TracesGetAnalyticsSummaryResponseTopFunctionsItem
> = core.serialization.object({
  functionName: core.serialization.string(),
  count: core.serialization.number(),
});

export declare namespace TracesGetAnalyticsSummaryResponseTopFunctionsItem {
  export interface Raw {
    functionName: string;
    count: number;
  }
}
