// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";
import { TracesSearchByEnvRequestAttributeFiltersItemOperator } from "./TracesSearchByEnvRequestAttributeFiltersItemOperator.js";

export const TracesSearchByEnvRequestAttributeFiltersItem: core.serialization.ObjectSchema<
  serializers.TracesSearchByEnvRequestAttributeFiltersItem.Raw,
  Mirascope.TracesSearchByEnvRequestAttributeFiltersItem
> = core.serialization.object({
  key: core.serialization.string(),
  operator: TracesSearchByEnvRequestAttributeFiltersItemOperator,
  value: core.serialization.string().optional(),
});

export declare namespace TracesSearchByEnvRequestAttributeFiltersItem {
  export interface Raw {
    key: string;
    operator: TracesSearchByEnvRequestAttributeFiltersItemOperator.Raw;
    value?: string | null;
  }
}
