// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";
import { TracesGetTraceDetailResponseSpansItem } from "./TracesGetTraceDetailResponseSpansItem.js";

export const TracesGetTraceDetailResponse: core.serialization.ObjectSchema<
  serializers.TracesGetTraceDetailResponse.Raw,
  Mirascope.TracesGetTraceDetailResponse
> = core.serialization.object({
  traceId: core.serialization.string(),
  spans: core.serialization.list(TracesGetTraceDetailResponseSpansItem),
  rootSpanId: core.serialization.string().nullable(),
  totalDurationMs: core.serialization.number().nullable(),
});

export declare namespace TracesGetTraceDetailResponse {
  export interface Raw {
    traceId: string;
    spans: TracesGetTraceDetailResponseSpansItem.Raw[];
    rootSpanId?: string | null;
    totalDurationMs?: number | null;
  }
}
