// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";
import { TracesCreateOtelRequestResourceSpansItemResourceAttributesItem } from "./TracesCreateOtelRequestResourceSpansItemResourceAttributesItem.js";

export const TracesCreateOtelRequestResourceSpansItemResource: core.serialization.ObjectSchema<
  serializers.TracesCreateOtelRequestResourceSpansItemResource.Raw,
  Mirascope.TracesCreateOtelRequestResourceSpansItemResource
> = core.serialization.object({
  attributes: core.serialization
    .list(TracesCreateOtelRequestResourceSpansItemResourceAttributesItem)
    .optional(),
  droppedAttributesCount: core.serialization.number().optional(),
});

export declare namespace TracesCreateOtelRequestResourceSpansItemResource {
  export interface Raw {
    attributes?:
      | TracesCreateOtelRequestResourceSpansItemResourceAttributesItem.Raw[]
      | null;
    droppedAttributesCount?: number | null;
  }
}
