// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";

export const TracesSearchByEnvRequestSortBy: core.serialization.Schema<
  serializers.TracesSearchByEnvRequestSortBy.Raw,
  Mirascope.TracesSearchByEnvRequestSortBy
> = core.serialization.enum_(["start_time", "duration_ms", "total_tokens"]);

export declare namespace TracesSearchByEnvRequestSortBy {
  export type Raw = "start_time" | "duration_ms" | "total_tokens";
}
