// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";

export const TagsCreateResponse: core.serialization.ObjectSchema<
  serializers.TagsCreateResponse.Raw,
  Mirascope.TagsCreateResponse
> = core.serialization.object({
  id: core.serialization.string(),
  name: core.serialization.string(),
  projectId: core.serialization.string(),
  organizationId: core.serialization.string(),
  createdBy: core.serialization.string().nullable(),
  createdAt: core.serialization.string().nullable(),
  updatedAt: core.serialization.string().nullable(),
});

export declare namespace TagsCreateResponse {
  export interface Raw {
    id: string;
    name: string;
    projectId: string;
    organizationId: string;
    createdBy?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
  }
}
