// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../api/index.js";
import type * as serializers from "../../../index.js";

import * as core from "../../../../core/index.js";
import { Date_ } from "../../../types/Date_.js";
import { OrganizationInvitationsGetResponseRole } from "./OrganizationInvitationsGetResponseRole.js";
import { OrganizationInvitationsGetResponseStatus } from "./OrganizationInvitationsGetResponseStatus.js";

export const OrganizationInvitationsGetResponse: core.serialization.ObjectSchema<
  serializers.OrganizationInvitationsGetResponse.Raw,
  Mirascope.OrganizationInvitationsGetResponse
> = core.serialization.object({
  id: core.serialization.string(),
  organizationId: core.serialization.string(),
  senderId: core.serialization.string(),
  recipientEmail: core.serialization.string(),
  role: OrganizationInvitationsGetResponseRole,
  status: OrganizationInvitationsGetResponseStatus,
  expiresAt: Date_,
  createdAt: Date_,
  updatedAt: Date_,
  acceptedAt: Date_.nullable(),
  revokedAt: Date_.nullable(),
});

export declare namespace OrganizationInvitationsGetResponse {
  export interface Raw {
    id: string;
    organizationId: string;
    senderId: string;
    recipientEmail: string;
    role: OrganizationInvitationsGetResponseRole.Raw;
    status: OrganizationInvitationsGetResponseStatus.Raw;
    expiresAt: Date_.Raw;
    createdAt: Date_.Raw;
    updatedAt: Date_.Raw;
    acceptedAt?: Date_.Raw | null;
    revokedAt?: Date_.Raw | null;
  }
}
