// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../api/index.js";
import type * as serializers from "../index.js";

import * as core from "../../core/index.js";

export const BigInt: core.serialization.Schema<
  serializers.BigInt.Raw,
  Mirascope.BigInt
> = core.serialization.string();

export declare namespace BigInt {
  export type Raw = string;
}
