// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../api/index.js";
import type * as serializers from "../index.js";

import * as core from "../../core/index.js";

export const ClickHouseError: core.serialization.ObjectSchema<
  serializers.ClickHouseError.Raw,
  Mirascope.ClickHouseError
> = core.serialization.object({
  message: core.serialization.string(),
  cause: core.serialization.unknown().optional(),
});

export declare namespace ClickHouseError {
  export interface Raw {
    message: string;
    cause?: unknown | null;
  }
}
