// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../api/index.js";
import type * as serializers from "../index.js";

import * as core from "../../core/index.js";
import { DatabaseErrorTag } from "./DatabaseErrorTag.js";

export const DatabaseError: core.serialization.ObjectSchema<
  serializers.DatabaseError.Raw,
  Mirascope.DatabaseError
> = core.serialization.object({
  message: core.serialization.string(),
  cause: core.serialization.unknown().optional(),
  tag: DatabaseErrorTag,
});

export declare namespace DatabaseError {
  export interface Raw {
    message: string;
    cause?: unknown | null;
    tag: DatabaseErrorTag.Raw;
  }
}
