// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../api/index.js";
import type * as serializers from "../index.js";

import * as core from "../../core/index.js";
import { IssueTag } from "./IssueTag.js";
import { PropertyKey } from "./PropertyKey.js";

export const Issue: core.serialization.ObjectSchema<
  serializers.Issue.Raw,
  Mirascope.Issue
> = core.serialization.object({
  tag: IssueTag,
  path: core.serialization.list(PropertyKey),
  message: core.serialization.string(),
});

export declare namespace Issue {
  export interface Raw {
    tag: IssueTag.Raw;
    path: PropertyKey.Raw[];
    message: string;
  }
}
