// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../api/index.js";
import type * as serializers from "../index.js";

import * as core from "../../core/index.js";

export const StripeErrorTag: core.serialization.Schema<
  serializers.StripeErrorTag.Raw,
  Mirascope.StripeErrorTag
> = core.serialization.enum_(["StripeError"]);

export declare namespace StripeErrorTag {
  export type Raw = "StripeError";
}
