# This file was auto-generated by Fern from our API Definition.

import typing

ClawsListResponseItemStatus = typing.Union[
    typing.Literal["pending", "provisioning", "active", "paused", "error"], typing.Any
]
