# This file was auto-generated by Fern from our API Definition.

import typing

ClawsCreateResponseInstanceType = typing.Union[
    typing.Literal[
        "lite", "basic", "standard-1", "standard-2", "standard-3", "standard-4"
    ],
    typing.Any,
]
