import {
  createStartHandler,
  defaultStreamHandler,
} from "@tanstack/react-start/server";

import { handleRedirect } from "@/redirects";

/**
 * Handle markdown content negotiation.
 *
 * When a request includes `Accept: text/markdown`, attempts to serve
 * the pre-generated .md file from static assets instead of HTML.
 *
 * This enables LLM clients to fetch documentation in markdown format,
 * reducing token usage compared to HTML.
 *
 * @param request - The incoming request
 * @param environment - Cloudflare Worker environment with ASSETS binding
 * @returns Response with markdown content, or null if no .md file exists
 */
async function handleMarkdownRequest(
  request: Request,
  environment: { ASSETS: { fetch: (req: Request) => Promise<Response> } },
): Promise<Response | null> {
  const url = new URL(request.url);
  let pathname = url.pathname;

  // Normalize pathname: remove trailing slash
  if (pathname.endsWith("/") && pathname.length > 1) {
    pathname = pathname.slice(0, -1);
  }

  // Only handle content pages that might have markdown files
  // These are generated by the markdown-export plugin for docs, blog, policy, and pricing pages
  const contentPrefixes = [
    "/docs/",
    "/blog/",
    "/privacy",
    "/terms/",
    "/pricing",
  ];
  const isContentPath = contentPrefixes.some(
    (prefix) => pathname.startsWith(prefix) || pathname === prefix.slice(0, -1),
  );

  if (!isContentPath) {
    return null;
  }

  // Construct the markdown file path
  // e.g., /docs/learn/llm/calls -> /docs/learn/llm/calls.md
  const mdPath = `${pathname}.md`;

  // Try to fetch the .md file from static assets
  const mdUrl = new URL(mdPath, url.origin);
  const mdRequest = new Request(mdUrl.toString(), {
    method: "GET",
    headers: request.headers,
  });

  try {
    const response = await environment.ASSETS.fetch(mdRequest);

    if (response.ok) {
      // Return markdown with appropriate Content-Type
      return new Response(response.body, {
        status: 200,
        headers: {
          "Content-Type": "text/markdown; charset=utf-8",
          "Cache-Control":
            response.headers.get("Cache-Control") ?? "public, max-age=3600",
        },
      });
    }
  } catch {
    // ASSETS binding not available or fetch failed, fall through
  }

  return null;
}

const fetchHandler = createStartHandler(defaultStreamHandler);

interface WorkerEnv {
  ASSETS: { fetch: (req: Request) => Promise<Response> };
  ENVIRONMENT?: string;
}

const fetch = async (
  request: Request,
  environment: WorkerEnv,
): Promise<Response> => {
  // Handle programmatic redirects
  const redirectResponse = handleRedirect(request);
  if (redirectResponse) {
    return redirectResponse;
  }

  // Handle markdown content negotiation
  // When clients send Accept: text/markdown, serve the pre-generated .md file
  const acceptHeader = request.headers.get("Accept") ?? "";
  if (acceptHeader.includes("text/markdown")) {
    const markdownResponse = await handleMarkdownRequest(request, environment);
    if (markdownResponse) {
      return markdownResponse;
    }
    // Fall through to normal handler if no .md file exists
  }

  return fetchHandler(request);
};

export default {
  fetch,
};
