// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../index.js";

export interface ClawMembershipsGetResponse {
  memberId: string;
  organizationId: string;
  clawId: string;
  role: Mirascope.ClawMembershipsGetResponseRole;
  createdAt: Mirascope.Date_ | null;
}
