// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../../api/index.js";
import type * as serializers from "../../../../index.js";

import * as core from "../../../../../core/index.js";
import { TracesSearchRequestAttributeFiltersItem } from "../../types/TracesSearchRequestAttributeFiltersItem.js";
import { TracesSearchRequestSortBy } from "../../types/TracesSearchRequestSortBy.js";
import { TracesSearchRequestSortOrder } from "../../types/TracesSearchRequestSortOrder.js";

export const TracesSearchRequest: core.serialization.Schema<
  serializers.TracesSearchRequest.Raw,
  Mirascope.TracesSearchRequest
> = core.serialization.object({
  startTime: core.serialization.string(),
  endTime: core.serialization.string(),
  query: core.serialization.string().optional(),
  inputMessagesQuery: core.serialization.string().optional(),
  outputMessagesQuery: core.serialization.string().optional(),
  fuzzySearch: core.serialization.boolean().optional(),
  traceId: core.serialization.string().optional(),
  spanId: core.serialization.string().optional(),
  model: core.serialization.list(core.serialization.string()).optional(),
  provider: core.serialization.list(core.serialization.string()).optional(),
  functionId: core.serialization.string().optional(),
  functionName: core.serialization.string().optional(),
  spanNamePrefix: core.serialization.string().optional(),
  hasError: core.serialization.boolean().optional(),
  minTokens: core.serialization.number().optional(),
  maxTokens: core.serialization.number().optional(),
  minDuration: core.serialization.number().optional(),
  maxDuration: core.serialization.number().optional(),
  attributeFilters: core.serialization
    .list(TracesSearchRequestAttributeFiltersItem)
    .optional(),
  limit: core.serialization.number().optional(),
  offset: core.serialization.number().optional(),
  sortBy: TracesSearchRequestSortBy.optional(),
  sortOrder: TracesSearchRequestSortOrder.optional(),
  rootSpansOnly: core.serialization.boolean().optional(),
});

export declare namespace TracesSearchRequest {
  export interface Raw {
    startTime: string;
    endTime: string;
    query?: string | null;
    inputMessagesQuery?: string | null;
    outputMessagesQuery?: string | null;
    fuzzySearch?: boolean | null;
    traceId?: string | null;
    spanId?: string | null;
    model?: string[] | null;
    provider?: string[] | null;
    functionId?: string | null;
    functionName?: string | null;
    spanNamePrefix?: string | null;
    hasError?: boolean | null;
    minTokens?: number | null;
    maxTokens?: number | null;
    minDuration?: number | null;
    maxDuration?: number | null;
    attributeFilters?: TracesSearchRequestAttributeFiltersItem.Raw[] | null;
    limit?: number | null;
    offset?: number | null;
    sortBy?: TracesSearchRequestSortBy.Raw | null;
    sortOrder?: TracesSearchRequestSortOrder.Raw | null;
    rootSpansOnly?: boolean | null;
  }
}
