// This file was auto-generated by Fern from our API Definition.

export const OrganizationInvitationsGetResponseRole = {
  Admin: "ADMIN",
  Member: "MEMBER",
} as const;
export type OrganizationInvitationsGetResponseRole =
  (typeof OrganizationInvitationsGetResponseRole)[keyof typeof OrganizationInvitationsGetResponseRole];
