// This file was auto-generated by Fern from our API Definition.

export const OrganizationInvitationsListResponseItemStatus = {
  Pending: "pending",
  Accepted: "accepted",
  Revoked: "revoked",
} as const;
export type OrganizationInvitationsListResponseItemStatus =
  (typeof OrganizationInvitationsListResponseItemStatus)[keyof typeof OrganizationInvitationsListResponseItemStatus];
