// This file was auto-generated by Fern from our API Definition.

export const OrganizationInvitationsCreateResponseStatus = {
  Pending: "pending",
  Accepted: "accepted",
  Revoked: "revoked",
} as const;
export type OrganizationInvitationsCreateResponseStatus =
  (typeof OrganizationInvitationsCreateResponseStatus)[keyof typeof OrganizationInvitationsCreateResponseStatus];
