// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../index.js";

export interface FunctionsCreateResponse {
  id: string;
  hash: string;
  signatureHash: string;
  name: string;
  description: string | null;
  version: string;
  tags: string[] | null;
  metadata: Record<string, string | null> | null;
  code: string;
  signature: string;
  language: string;
  dependencies: Record<
    string,
    Mirascope.FunctionsCreateResponseDependenciesValue | null
  > | null;
  environmentId: string;
  projectId: string;
  organizationId: string;
  createdAt: string | null;
  updatedAt: string | null;
}
