// This file was auto-generated by Fern from our API Definition.

import type * as Mirascope from "../../../../../api/index.js";
import type * as serializers from "../../../../index.js";

import * as core from "../../../../../core/index.js";
import { TokenCostCalculateRequestUsage } from "../../types/TokenCostCalculateRequestUsage.js";

export const TokenCostCalculateRequest: core.serialization.Schema<
  serializers.TokenCostCalculateRequest.Raw,
  Mirascope.TokenCostCalculateRequest
> = core.serialization.object({
  provider: core.serialization.string(),
  model: core.serialization.string(),
  usage: TokenCostCalculateRequestUsage,
  viaRouter: core.serialization.boolean().optional(),
});

export declare namespace TokenCostCalculateRequest {
  export interface Raw {
    provider: string;
    model: string;
    usage: TokenCostCalculateRequestUsage.Raw;
    viaRouter?: boolean | null;
  }
}
